### ISSUE TITLE
[Insight] The composer.json file should not raise warnings - in composer.json, line 0

### ISSUE THREAD

**Issue by aasanchez** [symfony/symfony-standard#1007]
**[in composer.json](https://github.com/symfony/symfony-standard/blob/c5c8c32b933bea904930de38f005b462d06ff6b5/composer.json#L0)**

> Defining autoload.psr-4 with an empty namespace prefix is a bad idea for performance

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/446df8f8-528a-4cfd-a80b-262e0e7441f2/analyses/494)_

**Comment by arderyp** [comment]
Can we get an explanation on the closing of this issue?  I have the same warning and, while it is only a warning, I too think the composer.json generated from `symfony new <project>` should not throw warnings right out of the gate.

```
$ symfony new test_blog

 Downloading Symfony...

    5.3 MiB/5.3 MiB ▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓▓  100%

 Preparing project...

 ✔  Symfony 3.2.2 was successfully installed. Now you can:

    * Change your current directory to /home/arderyp/test/test_blog

    * Configure your application in app/config/parameters.yml file.

    * Run your application:
        1. Execute the php bin/console server:start command.
        2. Browse to the http://localhost:8000 URL.

    * Read the documentation at http://symfony.com/doc


$ cd test_blog/

$ composer diagnose
Checking composer.json: WARNING
Defining autoload.psr-4 with an empty namespace prefix is a bad idea for performance
Checking platform settings: OK
Checking git settings: OK
Checking http connectivity to packagist: OK
Checking https connectivity to packagist: OK
Checking github.com rate limit: OK
Checking disk free space: OK
Checking pubkeys: 
Tags Public Key Fingerprint: 57815BA2 7E54DC31 7ECC7CC5 573090D0  87719BA6 8F3BB723 4E5D42D0 84A14642
Dev Public Key Fingerprint: 4AC45767 E5EC2265 2F0C1167 CBBB8A2B  0C708369 153E328C AD90147D AFE50952
OK
Checking composer version: OK
```

Is there a suggested solution for standard, project-level composer.json, as opposed to third-party bundles which usually do have a name space here.  Or is the official advice to ignore the warning?

**Comment by Pierstoval** [comment]
@arderyp I don't know about an official advice for this issue, but what's sure is that you can safely ignore the warning for your application.

**Comment by arderyp** [comment]
Great, thanks for the feedback!

**Comment by aasanchez** [comment]
I have the same issue for a long time, I never figurate why, but honestly I don't think that it's a god advice ignore the warnings
