### ISSUE TITLE
Authorization voters missing in 3.1

### ISSUE THREAD

**Issue by dspiegel** [symfony/symfony-standard#1014]
Just upgraded from 3.0.9 to 3.1 and was not expecting any problems, but my app can no longer log in. I've looked for others having same type of issue and spent several days trying to determine what might have changed.

I'm really not sure where the problem starts, but what occurs is:

**Token does not have the required roles**.
403 Forbidden - AccessDeniedHttpException
1 linked Exception: AccessDeniedException »

I am using GuardAuthenticator with a token. It appears as if all the Roles and User are being created as expected, but then Authorization fails. The user has proper Roles to access page.

I traced the actually point of failure at JMS\SecurityExtraBundle\Security\Authorization\Interception 
accessDecisionManager->decide call. I see no changes that were done to this code from 3.0.9 to 3.1.5.
```
if (!empty($metadata->roles) && false === $this->accessDecisionManager->decide($token, $metadata->roles, $method)) {
            throw new AccessDeniedException('Token does not have the required roles.');
 }
```
accessDecisionManager->decide() resides in Symfony\Component\Security\Core\Authorization class 
which calls decideAffirmative(TokenInterface $token, array $attributes, $object = null)

Version 3.0.9 has 4 different Voters at this point (_decideAffirmative_) which provide a true (success) response.
```
array:4 [▼
  0 => LazyLoadingExpressionVoter {#458 ▶}
  1 => ExpressionVoter {#454 ▶}
  2 => RoleHierarchyVoter {#431 ▶}
  3 => AuthenticatedVoter {#434 ▶}
]
```
While Version 3.1.5 has 0 Voters which caused false return and failed login.

So something happened from 3.0 -> 3.1 which caused BC because the 4 default voters from 3.0.9 are gone.

Perhaps I missed something when setting up Guard, but I cannot find any demo's or examples for Guard other than using Symfony 2.8 or 3.0.

Any help to understand what might have caused this would be appreciated. Do I need to now create these Voters for my app?

Thanks, Dave

**Comment by bocharsky-bw** [comment]
Hey @dspiegel , thank you for this report, but I think this issue should be opened in https://github.com/symfony/symfony repository.

**Comment by dspiegel** [comment]
Moved issue to: symfony/symfony#20211
