### ISSUE TITLE
file classes.php not generated

### ISSUE THREAD

**Issue by ricpar123** [symfony/symfony-standard#1015]
After creating and installing successfully a new project, even running demo app without errors, when try to run app created, error showing "can not write on /path/to/my/project/app/cache/dev/classes.php".
And it is not a permission error, the file classes.php do not exist...???? This file is not create as a installation process???
Try  to find some similar in the forums, i couldn't find nothing relative to this issue.
What is wrong? I use symfony version 2.8, ubuntu 16.01. 
I also update composer, clean cache, .... but nothing ..always same error.

**Comment by flug** [comment]
You are try : http://symfony.com/doc/current/setup/file_permissions.html  ?

**Comment by ricpar123** [comment]
The problem is not file's permission.

The file classes.php do not exist!!.....obviously it can't write to it!

**Comment by xabbuh** [comment]
@ricpar123 Can you please show the exact error message and possibly also a full stack trace?

**Comment by ricpar123** [comment]
Yes, of course....following it is...".RuntimeException in ClassCollectionLoader.php line 239: Failed to write cache file "/var/www/html/miproj/app/cache/dev/classes.php"."
and a lot of error messages from php....
As I said, i checked the /app/cache/dev directory and classes.php is not there...!
thanks for your attention

**Comment by bocharsky-bw** [comment]
Hey @ricpar123 , so how have you solved it?

**Comment by ricpar123** [comment]
I couldn't yet. I am working on that.
