### ISSUE TITLE
Rename DefaultController to MainController?

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony-standard#1016]
The current name somewhat implies _that_ controller is used by _default_ throughout the system. Ie. a catch-all controller, but it isnt.

Imo `MainController` suits better.

Any thoughts?

**Comment by Tobion** [comment]
You should rename the controller anyway. So it doesn't matter what it's called.

**Comment by ro0NL** [comment]
Im not sure, `AppBundle\DefaultController::indexction` looks like a common entrypoint to me, for any type of application. Only i would name it `MainController`, and perhaps even `MainController::homepageAction`.

**Comment by fabpot** [comment]
Is it really worth it? I mean, tutorials, documentation mention this, so renaming should only be done if it gives us something much better. I don't think this is the case here. So, closing it.
