### ISSUE TITLE
The config has to be updated to fit with Twig deprecated

### ISSUE THREAD

**Issue by gregquat** [symfony/symfony-standard#1017]
Twig 1.27 has been released yesterday and introduces some deprecated call.
For example, this error occured on all pages of my application :
`Using "filename" as the default strategy is deprecated since version 1.27. Use "name" instead`

The default value of the autoescape parameter seems to be changed also in the Standard Edition to avoid the warnings.

```
twig:
    autoescape: name
```

**Comment by xabbuh** [comment]
I do not see where we do configure this explicitly in the Standard Edition.

**Comment by gregquat** [comment]
Actually it's not configured, but the default value is "filename".
https://symfony.com/doc/current/reference/configuration/twig.html#autoescape

I don't really know if it's a bug or not. That's why I create an issue and not a PR.
I had a problem, so maybe it will be useful for somebody else.

**Comment by xabbuh** [comment]
I see, actually we just have to update the documentation here to reflect the changes done in symfony/symfony#20224.

**Comment by xabbuh** [comment]
The docs will be updated with symfony/symfony-docs#7089.
