### ISSUE TITLE
[Cache] apcu_bc needed when upgrading to PHP7

### ISSUE THREAD

**Issue by rvanlaak** [symfony/symfony-standard#1018]
We recently upgraded to PHP7, and are working on migrating to Redis, but in the meanwhile we still need APCu. Although I remember that APC support would be dropped with Symfony 3.0 this still left some traces. This required us to install [`apcu_bc`](https://pecl.php.net/package/apcu_bc), because we still are in the process of migrating from 2.8 to 3.1 due to Sylius.

- There still are docs about enabling framework / [annotation](http://symfony.com/doc/current/reference/configuration/framework.html#reference-annotations-cache) / [validation](http://symfony.com/doc/current/reference/configuration/framework.html#reference-validation-cache) / [templating](http://symfony.com/doc/current/reference/configuration/framework.html#reference-templating-cache) caching. The 3.1 branch for instance mentions APC, but does not mention APCu.
- Core only has an `ApcAdapter` that implements the `CacheInterface`, there is no `ApcuAdapter`.
- A `apcu` caching service for Doctrine also is missing with [the options](http://symfony.com/doc/current/reference/configuration/doctrine.html#caching-drivers).

Right now I'm working on implementing my own apcu adapter service, but can this be considered something that should be added to 2.8+ too? If so, we thereafter can get rid of the `apcu_bc` package.

**Comment by Tobion** [comment]
Is this in symfony-standard by mistake?

**Comment by rvanlaak** [comment]
Ah yes, you're right ... now I see the Framework bundle is split from [`symfony/symfony`](https://github.com/symfony/symfony/tree/master/src/Symfony/Bundle/FrameworkBundle). Closed in favor of https://github.com/symfony/symfony/issues/20373
