### ISSUE TITLE
Incorrect documentation links in the README

### ISSUE THREAD

**Issue by mvar** [symfony/symfony-standard#1021]
For example, `SecurityBundle` links to <https://symfony.com/doc/3.0/book/security.html> (Page Not Found), should link to <https://symfony.com/doc/current/security.html>.

**Comment by Tobion** [comment]
Would you mind opening a PR?

**Comment by wouterj** [comment]
Btw, these links should redirect to the new articles normally. That's a bug on the symfony.com side and I've reported it now. Thanks for catching it!

But yes, it's better to update the links to the new locations. This should be done in the 2.7 branch first. These links are probably redirected, so it'll be a bit easier to update the links.
