### ISSUE TITLE
[Q/IDEA] move configuration folder inside of Resources directory

### ISSUE THREAD

**Issue by namaless** [symfony/symfony-standard#1024]
I was thinking to post this comment but in the end I do it.

In the bundles we found the `config` folder inside the `Resources` directory and is the same in the app directory (for Resources folder), so I think: isn't much better reuse the same situation for the application moving the `config` folder inside the `Resources` directory?

I don't check anything but I think we need few modifications to do it (one for sure into the generator bundle), thanks for check this idea.

**Comment by Pierstoval** [comment]
`app/Resources/config` seems too long to me to handle whereas `app/config` is very straightforward.

The `app` folder does not respect the Bundle directory structure because it's not a bundle at all, it's the core of your app.

**Comment by fabpot** [comment]
Closing as changes like that should happen on the new symfony/skeleton, symfony/flex repos.
