### ISSUE TITLE
Using Doctrine with the 3.2 branch

### ISSUE THREAD

**Issue by abhinavkumar940** [symfony/symfony-standard#1029]
After upgrading to `3.2.x` I am not able to find a stable/compatible version of `Doctrine/Common` to use.

`php bin/console cache:clear` gives me 
`
[ReflectionException]                                                    
    Class Doctrine\Common\Proxy\AbstractProxyFactory does not exist
`

As the `Doctrine/Common` component is no longer there in the vendors dir. But when I try to install it manually by
`composer require doctrine/common` I get

````
Your requirements could not be resolved to an installable set of packages.

Problem 1
    - doctrine/dbal v2.5.5 requires doctrine/common >=2.4,<2.7-dev -> satisfiable by doctrine/common[2.4.0-RC1, 2.4.0-RC2, 2.4.0-RC3, 2.4.0-RC4, 2.4.x-dev, 2.5.x-dev, 2.6.x-dev, v2.4.0, v2.4.1, v2.4.2, v2.4.3, v2.5.0, v2.5.0-beta1, v2.5.1, v2.5.2, v2.5.3, v2.6.0, v2.6.1, v2.6.2] but these conflict with your requirements or minimum-stability.
    - doctrine/dbal v2.5.5 requires doctrine/common >=2.4,<2.7-dev -> satisfiable by doctrine/common[2.4.0-RC1, 2.4.0-RC2, 2.4.0-RC3, 2.4.0-RC4, 2.4.x-dev, 2.5.x-dev, 2.6.x-dev, v2.4.0, v2.4.1, v2.4.2, v2.4.3, v2.5.0, v2.5.0-beta1, v2.5.1, v2.5.2, v2.5.3, v2.6.0, v2.6.1, v2.6.2] but these conflict with your requirements or minimum-stability.
    - doctrine/dbal v2.5.5 requires doctrine/common >=2.4,<2.7-dev -> satisfiable by doctrine/common[2.4.0-RC1, 2.4.0-RC2, 2.4.0-RC3, 2.4.0-RC4, 2.4.x-dev, 2.5.x-dev, 2.6.x-dev, v2.4.0, v2.4.1, v2.4.2, v2.4.3, v2.5.0, v2.5.0-beta1, v2.5.1, v2.5.2, v2.5.3, v2.6.0, v2.6.1, v2.6.2] but these conflict with your requirements or minimum-stability.
    - Installation request for doctrine/dbal (locked at v2.5.5) -> satisfiable by doctrine/dbal[v2.5.5].
````

[my composer.json](https://gist.github.com/abhinavkumar940/387f4da8c9ec31dfcca13823d5ebabeb)

**Comment by stof** [comment]
not having doctrine/common while you have doctrine/dbal looks suspicious to me

**Comment by abhinavkumar940** [comment]
Thanks for your prompt response.

Yeah, that's actually part of the problem and how it was during the 3.1.x
days.
It even works for the 3.2.x-dev branch but not with the stable 3.2

I'm aware they removed some dependencies, just not sure how it should look
like for an existing project.

**Comment by stof** [comment]
well, I just cannot understand how you end up having doctrine/dbal without doctrine/common, as doctrine/dbal requires doctrine/common. This is just impossible when using composer

**Comment by stof** [comment]
And if you use ``composer require doctrine/common``, this indeed creates a conflict, because composer will guess the requirement as being ``^2.7.0`` as doctrine/common 2.7.0 has been released 2 days ago, but doctrine/dbal and doctrine/orm don't have releases allowing it yet

**Comment by abhinavkumar940** [comment]
That's because 3.2 removed some dependencies and suggested to load them as
and when required.

Doctrine/common was removed as part of the upgrade process as the 3.2
doesn't list that as one of the dependencies.

Ideally, I should be able to install them manually after the upgrade but
that's what I'm having problem with

**Comment by abhinavkumar940** [comment]
Exactly my problem.

I was thinking I can probably hard code the last stable version for those
components in my composer.json

You think it'll work?

**Comment by stof** [comment]
@abhinavkumar940 but if you are using doctrine/dbal, composer would not have removed doctrine/dbal from your own project, as it is still needed. This is why I don't understand how it could have disappeared from the vendor folder (unless you changed this folder manually instead of letting composer manage it)

**Comment by abhinavkumar940** [comment]
I never change anything from the vendors folder so that's out of the
question.

What I can do is get back to the 3.2.x-dev branch, check the folder
structure and then back to the 3.2.x stable and then will compare what's
going on.

Unfortunately I'll be able to that tomorrow. I'll update the issue with my
findings.

Thanks again for bearing with me this far.

**Comment by xabbuh** [comment]
@abhinavkumar940 How did you solve your issue?
