### ISSUE TITLE
Wire WebServerbundle for 3.3

### ISSUE THREAD

**Issue by chalasr** [symfony/symfony-standard#1041]
Reminder: 
Once symfony/symfony 3.3  is released, we should register the WebServerBundle (AppKernel) when updating vendors, so the `server:*` commands are available. Same for the [symfony-demo](/symfony/symfony-demo) repository and any "demo" project which makes use of these commands.

**Comment by fabpot** [comment]
It can be done already on the master branch which requires 3.3. Can you do a PR?

**Comment by chalasr** [comment]
@fabpot vendors are locked to 3.2.1, I thought it should stay as is hence this issue. See #1042
