### ISSUE TITLE
Email validation and SwiftMailer

### ISSUE THREAD

**Issue by murilolobato** [symfony/symfony-standard#1061]
Currently, the Email constraint validates against RFC 6530, which allows special characters in email address, while the current SwiftMailer supports only RFC2822. This leads to an exception if the users tries to registrate with an email address with a special character. e.g.: 'müller@someprovider.de'

**Comment by Pierstoval** [comment]
Please post this issue in https://github.com/swiftmailer/swiftmailer instead

**Comment by murilolobato** [comment]
I don't think it is a SwiftMailer problem. The fact is that swift mailer is RFC 2822 compliant, and the constraint\email (when strict=true) is RFC6530 compliant. None of those alone has problem. But when they're shipped together, the developer must be advised about this fact. Otherwise, it will frustrate the developer because the mailer will dispatch a error in an address that the framework said it was validated strictly.

Also, this is not limited to SwiftMailer, others ESP's are limited to RFC 2822, as is sendgrid.net.

https://github.com/egulias/EmailValidator/issues/145

**Comment by Pierstoval** [comment]
Still, this issue has no place in Symfony Standard. 

If this is a bug from Swiftmailer not sending emails (and I think it is), post this issue on [swiftmailer/swiftmailer][https://github.com/swiftmailer/swiftmailer/issues/new?title=Issue%20with%20RFC%20compliancy), else, if you think it's a Symfony issue, post it to [symfony/symfony](https://github.com/symfony/symfony/issues/new?title=[Swiftmailer]%20Issue%20with%20RFC%20compliancy)

**Comment by fabpot** [comment]
Closing as there have been discussions on this on symfony/symfony.
