### ISSUE TITLE
Why assetic still exists in composer.json?

### ISSUE THREAD

**Issue by edwines** [symfony/symfony-standard#1062]
If I am not mistaken the ascetic bundle was removed from the standard edition, right?

So I am confused when I see it in the composer file.

https://github.com/symfony/symfony-standard/blob/2.8/composer.json#L20

**Comment by jvasseur** [comment]
It is removed since version 3.0 so it's normal to still have it for the 2.8 version.

**Comment by xabbuh** [comment]
AsseticBundle was removed from the Symfony Standard Edition in 2.8 (see #860). However, it seemed to have accidentally put in again when 9363777a1e313dd64d4c2444b4527360eb5b778d was merged up in e210aa20138b863624714e4d99e1f566bd84d2ba.
