### ISSUE TITLE
[BUG] Symfony isn't updating the project when a file is changed

### ISSUE THREAD

**Issue by giancarloandroid** [symfony/symfony-standard#1067]
**Description**
Symfony isn't updating the project files.

**Pictures:**

**index.html.twig:** 
![selecao_738](https://cloud.githubusercontent.com/assets/8602136/25728393/27258366-3105-11e7-9140-3c8368550d47.png)

**http://192.168.50.4:8081:** 
![selecao_739](https://cloud.githubusercontent.com/assets/8602136/25728435/6b8b0346-3105-11e7-804d-931dce0335e0.png)

**Comment by hacfi** [comment]
@giancarloandroid You might be running in `prod` mode and there you need to clear the (twig) cache: `php bin/console cache:clear -e=prod` or if you run into permission issues doing that `rm -rf var/cache/prod` (less recommended but does the job)

**Comment by Pierstoval** [comment]
How is PHP run in your vagrant machine? Apache? Nginx? `bin/console server:run`?

**Comment by giancarloandroid** [comment]
Kginx, the problem is that @hacfi said. Thank you all!

**Comment by giancarloandroid** [comment]
@hacfi, how can I set dev enviroment instead prod enviroment to avoid clearing the cache all the time?

**Comment by hacfi** [comment]
@giancarloandroid Add a separate nginx server pointing to web/app_dev.php instead of web/app.php or try opening the the browser at http://localhost/app_dev.php/ instead or whatever your current url is add /app_dev.php/
