### ISSUE TITLE
Update phpunit.xml.dist to use KERNEL_CLASS

### ISSUE THREAD

**Issue by BPScott** [symfony/symfony-standard#1073]
symfony/symfony#22668 changed how we tell phpunit about where the Kernel lives - instead of passing a directory, explicitly state the FQCN of the Kernel ([the KERNEL_DIR method shall be deprecated as of 3.4](symfony/symfony/pull/22675)).

Once the vendors have been updated to include this change (it landed in master after 3.3.0-BETA1) change the following line in phpunit.xml.dist

```xml
<server name="KERNEL_DIR" value="app/" />
```

to 

```xml
 <server name="KERNEL_CLASS" value="AppKernel" />
```

**Comment by fabpot** [comment]
done in d290a6b

**Comment by vasilvestre** [comment]
I think this should be App\Kernel now instead of AppKernel

**Comment by lovrozitnik** [comment]
@vasilvestre You are right, the correct settings that works for me is:

<server name="KERNEL_CLASS" value="App\Kernel" />

**Comment by Pierstoval** [comment]
For Symfony 4 with Flex yes. 

Symfony-Standard, is still using the old SF2&3 architecture, therefore the FQCN of the kernel class is still `AppKernel`. Check the [app/AppKernel.php](https://github.com/symfony/symfony-standard/blob/3.4/app/AppKernel.php).

**Comment by vasilvestre** [comment]
Symfony standard end with 3.4
Couldn't it be done with recipes for flex?

**Comment by xabbuh** [comment]
I do not understand how this is related to Flex at all. And there is an existing recipe for PHPUnit: https://github.com/symfony/recipes/blob/f2d8bb6428ea81a71308e66974b6612004c7baf7/phpunit/phpunit/4.7/.env.test#L2 Is that what you are looking for?

**Comment by vasilvestre** [comment]
This is what I looked for. Why isn't it working ? I req phpunit bridge and I had to modify the file..

**Comment by SlimenTN** [comment]
Leaving this here just in case 
for symfony 4.3:
`<server name="KERNEL_CLASS" value="App\Kernel" />`
`App\Kernel` instead of `App\AppKernel`
