### ISSUE TITLE
Problem with Authorization header

### ISSUE THREAD

**Issue by matiux** [symfony/symfony-standard#1076]
Hi,
I have a problemi with passing of Authorization header.
In Sf 3.2.7 I was passing a header with Postman like this:
Authorization Bearer {token}

Now, in sf 3.2.8 the Authorization header doesn't arrive

I have a unit test that testing my controller and I have setup the client in this way and works
```
        $this->client->request('GET', "/Hotel/{$aHotel->id()->id()", [], [], [
            'HTTP_AUTHORIZATION' => "Bearer {$this->token}"
        ]);
```

Postman has stopped working

I thought that the htaccess should solve the problem with this lines:

```
    # Sets the HTTP_AUTHORIZATION header removed by Apache
    RewriteCond %{HTTP:Authorization} .
    RewriteRule ^ - [E=HTTP_AUTHORIZATION:%{HTTP:Authorization}]
```
But nothing to do...

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
