### ISSUE TITLE
Fatal error: Call to undefined method AppBundle\Controller\DefaultController::getParameter()

### ISSUE THREAD

**Issue by scion4581** [symfony/symfony-standard#1092]
Hello! I am a newguy in symfony. Am I something missing, but now cause DefaultController extends AbstractController, so in symfony-standard/src/AppBundle/Controller/DefaultController.php line 
18  --> 'base_dir' => realpath($this->getParameter('kernel.project_dir')).DIRECTORY_SEPARATOR,
throws exception in issue title, I guess AbstractController doesnt have getParameter method

Thanks

**Comment by stof** [comment]
@nicolas-grekas what is intended that `getParameter` stayed in Controller only rather than being in ControllerTrait to be there also in AbstractController ?

**Comment by nicolas-grekas** [comment]
AbstractController does gives access to a scoped PSR11 container, which doesn't have getParameter ().

**Comment by Picrrr** [comment]
Why just change the extend and do it on Controller ?

**Comment by yourithielen** [comment]
I can confirm this issue after installing Symfony 3.3.3 using the Symfony installer.

**Comment by xabbuh** [comment]
#1082 was reverted in c4c2ef5d383fd0a39adbb1eb5c8840a412fd4335.

**Comment by MustaphaGhlissi** [comment]
Hello 
J'ai le meme problème , mon controlleur étend de AbsctractController alors que la méthode getParameter n'existe plus

Que dois je faire ?

**Comment by javiereguiluz** [comment]
@MustaphaGhlissi please use the Symfony support channels to ask your question. See https://symfony.com/support  In the Symfony Slack, the `#support` channel is in English, but you'll find some channels in French where you can ask too. Thanks!
