### ISSUE TITLE
Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "AdminBundle" from namespace "AdminBundle".

### ISSUE THREAD

**Issue by speadup** [symfony/symfony-standard#1097]
Tag v3.3.3, I do this:

`composer.phar install`
`./bin/console  generate:bundle --namespace=AdminBundle  --dir=src --bundle-name=AdminBundle --format=yml --no-interaction`
`./bin/console cache:clear`

And I get this error:

PHP Fatal error:  Uncaught Symfony\Component\Debug\Exception\ClassNotFoundException: Attempted to load class "AdminBundle" from namespace "AdminBundle".
Did you forget a "use" statement for another namespace? in /disk/part-1/wwwroot/www/symfony-standard/app/AppKernel.php:19
Stack trace:
#0 /disk/part-1/wwwroot/www/symfony-standard/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(450): AppKernel->registerBundles()
#1 /disk/part-1/wwwroot/www/symfony-standard/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(116): Symfony\Component\HttpKernel\Kernel->initializeBundles()
#2 /disk/part-1/wwwroot/www/symfony-standard/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(137): Symfony\Component\HttpKernel\Kernel->boot()
#3 /disk/part-1/wwwroot/www/symfony-standard/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Console/Application.php(124): Symfony\Bundle\FrameworkBundle\Console\Application->registerCommands()
#4 /disk/part-1/wwwroot/www/symfony-standard/vendor in /disk/part-1/wwwroot/www/symfony-standard/app/AppKernel.php on line 19

**Comment by lyrixx** [comment]
Did you remove the cache folder ?

**Comment by speadup** [comment]
Yes, but no effect. I get same error.

**Comment by speadup** [comment]
See #1098

**Comment by fabpot** [comment]
Closing as a duplicate then.

**Comment by marciomrs4** [comment]
Fallow that steps https://github.com/symfony/symfony/issues/23547
