### ISSUE TITLE
SymfonyRequirements.php: create_function vulnerability

### ISSUE THREAD

**Issue by numediaweb** [symfony/symfony-standard#1102]
I am using Scrutinizer for code checking and it warns of the following error at [SymfonyRequirements.php:522](https://github.com/sensiolabs/SensioDistributionBundle/blob/0d0043cc5c3dd0e8ba5b365683586509bc7d3949/Resources/skeleton/app/SymfonyRequirements.php#L522)
 
> create_function can pose a great security vulnerability as it is similar to eval, and could be used for arbitrary code execution. We highly recommend to use a closure instead.

```
// Instead of
$function = create_function('$a, $b', 'return $a + $b');

// Better use
$function = function($a, $b) { return $a + $b; }
```

**Comment by Tobion** [comment]
This is required for PHP 5.2 compatibility. But IMO it's time to drop support for php 5.2 of the requirements checker.

**Comment by javiereguiluz** [comment]
Not sure if we should do that in the Standard Edition because it's about to be replaced by Symfony Flex. But let's fix this at least in Flex: https://github.com/symfony/requirements-checker/pull/11
