### ISSUE TITLE
config.platform.php version in composer.json

### ISSUE THREAD

**Issue by coudenysj** [symfony/symfony-standard#1103]
Is the "5.5.9" version supplied in composer.json (see 85a41df178d225) still required?

It holds back a lot of packages when updating.

**Comment by xabbuh** [comment]
Yes, we need this so that the pre-built packages used by the installer don't pull in dependencies that are not compatible with PHP 5.5. However, when you use the Symfony installer to set up a new Symfony project, this will removed anyway after the installation has finished.

**Comment by coudenysj** [comment]
Thanks for the feedback!
