### ISSUE TITLE
incorrect "accelerator should be installed" warning with APCu

### ISSUE THREAD

**Issue by FyiurAmron** [symfony/symfony-standard#1108]
As per https://stackoverflow.com/questions/29187601/difference-between-apc-apcu-and-opcache , APCu is feature-equivalent version of APC for PHP 5.5+, due to OpCache integration in PHP core. As such, the check in https://github.com/symfony/symfony-standard/blob/3.3/var/SymfonyRequirements.php#L717 should 
probably be

`            ( ( extension_loaded('apc') || extension_loaded('apcu') ) && ini_get('apc.enabled'))`

instead.

**Comment by Tobion** [comment]
apcu is not an accelerator as it does not include opcache as you said yourself. So the change you are proposing doesn't make sense.
