### ISSUE TITLE
Bad tag "v2.6." exists

### ISSUE THREAD

**Issue by andytson-inviqa** [symfony/symfony-standard#1112]
Please can you remove or correct this tag?

**Comment by andytson-inviqa** [comment]
I see, you have two tags:
v2.6.
7

I expect you meant to have one tag v2.6.7

**Comment by andytson-inviqa** [comment]
sorry ignore this, it appears this is an issue with a cache of the old tags which have been deleted

**Comment by stof** [comment]
The way Git works means that if you have this tag locally, you have to delete it for it to disappear. Fetching can bring new tags to your local clone, but it cannot remove any (this is a reason why deleting or replacing tags is a very bad idea in git once you pushed them)

**Comment by andytson-inviqa** [comment]
@stof no worries, it was a bug in the tool I was using, which cut off after 1024 bytes read in, which caused a newline to appear as it never expected output over that size
