### ISSUE TITLE
Attempted to call an undefined method named "findTaggedServiceIds" of class "appDevDebugProjectContainer".

### ISSUE THREAD

**Issue by mocrates** [symfony/symfony-standard#1113]
Hi,

I try to declare a service as

```
    AppBundle\Manager:
        arguments: ["@=container.findTaggedServiceIds('app.product.transformer')"]
```

In accord with the documentation https://symfony.com/doc/current/service_container/expression_language.html, we can access to ContainerBuilder in a Complex Expressions but it is instance of Container.

Is the documentation wrong or i miss somethings ?

To see code , i push it in my fork
https://github.com/mocrates/symfony-standard

thx

**Comment by Pierstoval** [comment]
Report to [symfony/symfony](https://github.com/symfony/symfony), and learn about DIC: the `findTaggedServiceIds()` method is only for the `ContainerBuilder`, not the generated `Container` class.

If you're using Symfony 3.4

**Comment by stof** [comment]
please report it to the doc repo. It is a bug in the doc. The expression has access to the container, not to the ContainerBuilder.

**Comment by mocrates** [comment]
thx @stof , it's done 

https://github.com/symfony/symfony-docs/pull/8534

**Comment by Tobion** [comment]
@mocrates it looks like this is what you might be interested in: http://symfony.com/blog/new-in-symfony-3-4-simpler-injection-of-tagged-services
