### ISSUE TITLE
Cannot download symfony standard edition.Versions 3.3.12 and 2.8.30

### ISSUE THREAD

**Issue by prbt2016** [symfony/symfony-standard#1116]
Hi ,
Observed that Symfony 3.3.12 and 2.8.30 are released : http://symfony.com/blog/ . However i am unable to download via the following links.
 http://symfony.com/download?v=Symfony_Standard_Vendors_3.3.12.zip
and 
http://symfony.com/download?v=Symfony_Standard_Vendors_2.8.30.zip
as the links show access denied .
Could you please resolve this issue.
Awaiting your kind reply.

**Comment by xabbuh** [comment]
see symfony/symfony-installer#298
