### ISSUE TITLE
app_dev.php access in docker

### ISSUE THREAD

**Issue by knyk** [symfony/symfony-standard#1118]
by default it cannot be accessed in standard docker configuration: php, nginx with vhost. IP is in range 172.16.0.0/12.

`
if (isset($_SERVER['HTTP_CLIENT_IP'])
    || isset($_SERVER['HTTP_X_FORWARDED_FOR'])
    || (isset($_SERVER['REMOTE_ADDR']) && filter_var(
        $_SERVER['REMOTE_ADDR'],
        FILTER_VALIDATE_IP,
        FILTER_FLAG_NO_PRIV_RANGE | FILTER_FLAG_NO_RES_RANGE
    ) !== false && PHP_SAPI !== 'cli-server')
    || (!isset($_SERVER['REMOTE_ADDR']) && PHP_SAPI !== 'cli-server')
) {
    header('HTTP/1.0 403 Forbidden');
    exit('You are not allowed to access this file. Check '.basename(__FILE__).' for more information.');
}
`

code above should allow all private IPs

**Comment by fabpot** [comment]
`app_dev.php` is meant to be changed. So, feel free to update the condition as you see fit. We won't change the code now as Flex has replaced the Standard Edition.
