### ISSUE TITLE
please help problem with swiftmailer 

### ISSUE THREAD

**Issue by anibalsoul** [symfony/symfony-standard#1119]
i make a website with drupal 8 and i need swift mailer but when i try to download the library with composer it's not working could anyone tell me why?

> C:\Users\Ahmoho\Sites\devdesktop\asso2>composer require swiftmailer/swiftmailer
> Using version ^6.0 for swiftmailer/swiftmailer
> ./composer.json has been updated
> Loading composer repositories with package information
> Updating dependencies (including require-dev)
> Your requirements could not be resolved to an installable set of packages.
> 
>   Problem 1
>     - Installation request for egulias/email-validator (installed at 1.2.14, required as ^1.2) -> satisfiable by egulias/email-validator[1.2.14].
>     - swiftmailer/swiftmailer 6.0.x-dev requires egulias/email-validator ~2.0 -> satisfiable by egulias/email-validator[2.0.x-dev].
>     - swiftmailer/swiftmailer v6.0.0 requires egulias/email-validator ~2.0 -> satisfiable by egulias/email-validator[2.0.x-dev].
>     - swiftmailer/swiftmailer v6.0.1 requires egulias/email-validator ~2.0 -> satisfiable by egulias/email-validator[2.0.x-dev].
>     - swiftmailer/swiftmailer v6.0.2 requires egulias/email-validator ~2.0 -> satisfiable by egulias/email-validator[2.0.x-dev].
>     - Conclusion: don't install egulias/email-validator 2.0.x-dev
>     - Installation request for swiftmailer/swiftmailer ^6.0 -> satisfiable by swiftmailer/swiftmailer[6.0.x-dev, v6.0.0, v6.0.1, v6.0.2].
> 
> 
> Installation failed, reverting ./composer.json to its original content.

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.
