### ISSUE TITLE
SensioDistributionBundle dependency question

### ISSUE THREAD

**Issue by twify93** [symfony/symfony-standard#1120]
So I found something interesting clearing up dependencies in the standard edition that we don't need for the project.
We are using 3.2, but this also applies for 3.3 as you will see from the Files and lines references:
Let's start with the [composer.json#21](https://github.com/symfony/symfony-standard/blob/3.3/composer.json#L21).
Going to the [AppKernel#24](https://github.com/symfony/symfony-standard/blob/3.3/app/AppKernel.php#L24) though, shows that this bundle is actually registered only when `test` or `dev` environments.

Any clue why is it setup like that? From what I can see that's wrong, but I haven't looked too deeply, just noticed it and wanted to ask.

Regards,
Lachezar Lechev

**Comment by Tobion** [comment]
Although you didn't ask a concrete question, I'll give some hints.
See command provided is not needed in production, see https://github.com/sensiolabs/SensioDistributionBundle/blob/master/Resources/config/security.xml that is why is in only active in dev/test.
But the composer scripts are always needed, see https://github.com/symfony/symfony-standard/blob/3.3/composer.json#L33. So it cannot be in require-dev.

For further questions, please use the support channels provided in http://symfony.com/support
