### ISSUE TITLE
Mark the repository as deprecated

### ISSUE THREAD

**Issue by falnyr** [symfony/symfony-standard#1121]
Could you add a line to readme saying that `symfony-standard` is no longer maintained for `4.0`? Lots of my friends use this repository as a source of truth.

**Comment by fabpot** [comment]
This repo is still maintained, but there is no version for 4.0. And you can see it pretty easily, there is no more master branch, not a 4.0 branch.

**Comment by Pierstoval** [comment]
Will it be maintained until the end of life of 3.x branches of the framework? We know there won't be new features, so maybe the standard edition could be kinda like "frozen" because it's working as-is? There's no bug to fix in here, actually 😕

**Comment by bocharsky-bw** [comment]
And probably makes sense to add a note to the README at least to explain why there's no Symfony 4.x available and how to get it, i.e. link to the http://symfony.com/download . I bet some devs may still go here to get the latest release because of habit

**Comment by fabpot** [comment]
@bocharsky-bw Can you submit a PR to add the warning in the README. I did something similar for SensioGeneratorBundle and SensioDistributionBundle.

**Comment by bocharsky-bw** [comment]
@fabpot Done in #1124

**Comment by bocharsky-bw** [comment]
Can we close it in favor of #1124 ?
