### ISSUE TITLE
No tag for 3.2.14

### ISSUE THREAD

**Issue by symfonyaml** [symfony/symfony-standard#1122]
Installation of the Standard Edition from composer works with version **3.2.13** but not with **3.2.14**
I didn't see any **3.2.14** tag, that is the cause I guess.

```
composer create-project symfony/framework-standard-edition test 3.2.14

[InvalidArgumentException]                                                      
  Could not find package symfony/framework-standard-edition with version 3.2.14.
```

**Comment by fabpot** [comment]
Indeed, we don't tag new versions after maintenance is over.  But you can still upgrade Symfony to 3.2.14 on any 3.2 version.
