### ISSUE TITLE
debug mode depends on empty string cli argument?

### ISSUE THREAD

**Issue by vkurdin** [symfony/symfony-standard#1125]
Enabling\disabling debug mode depends on empty string existence in cli argument. Why empty string? Is that a typo or what?

https://github.com/symfony/symfony-standard/blob/23416c9267d4581779f9b5bad6e780392c9845e9/bin/console#L19

Example:
```bash
bin/console some:command firstArgument ''
```
empty second argument suddenly turning debug mode off

**Comment by Tobion** [comment]
Fixed in https://github.com/symfony/symfony-standard/commit/126ce5784356a527852d00034b5dac3bb657773a
