### ISSUE TITLE
"Unable to find template X" with @Template annotation

### ISSUE THREAD

**Issue by Devtronic** [symfony/symfony-standard#1126]
Hello,

today I have created a new Symfony **3.4** project (`composer create-project symfony/framework-standard-edition`) and I have the following problem:
I have created a new controller with the command `php bin/console generate:controller AppBundle:Contact`. With the interactive mode I had created 3 actions: listAction, editAction and deleteAction. Everything is OK.
In the actions I replaced the `return $this->render(....)` with `return ['data' => 'foo']` and added the `@Template()` annotation.

Now this error is displayed:
`Unable to find template "@App/contact/list.html.twig" (looked into: /home/vagrant/Projects/backoffice/src/AppBundle/Resources/views).`
The reason is that the `generate:controller` command creates the file` AppBundle/Resources/views/Contact/list.html.twig`, but symfony is looking for `AppBundle/Resources/views/contact/list.html.twig` (lowercase letter c in contact).
Is this a wanted behavior or a bug?

**Comment by Pierstoval** [comment]
It's related to https://github.com/sensiolabs/SensioFrameworkExtraBundle actually, because the annotation is defined in this bundle.

**Comment by Devtronic** [comment]
@Pierstoval, thanks for the reference, i think found the reason: https://github.com/sensiolabs/SensioFrameworkExtraBundle/commit/82700a5a8cff6d8167f40a17c17591e1db2b38f1#diff-7cb1d2e06b631ebdc3c5471e12211ff9
