### ISSUE TITLE
Bundle generation

### ISSUE THREAD

**Issue by AlexandreSad** [symfony/symfony-standard#1132]
php bin/console generate:bundle

  Welcome to the Symfony bundle generator!

Are you planning on sharing this bundle across multiple applications? [no]: yes

Your application code must be written in bundles. This command helps
you generate them easily.

Each bundle is hosted under a namespace (like Acme/BlogBundle).
The namespace should begin with a "vendor" name like your company name, your
project name, or your client name, followed by one or more optional category
sub-namespaces, and it should end with the bundle name itself
(which must have Bundle as a suffix).

See http://symfony.com/doc/current/cookbook/bundles/best_practices.html#bundle-name for more
details on bundle naming conventions.

Use / instead of \ for the namespace delimiter to avoid any problems.

Bundle namespace: CA\TestBundle

In your code, a bundle is often referenced by its name. It can be the
concatenation of all namespace parts but it's really up to you to come
up with a unique name (a good practice is to start with the vendor name).
Based on the namespace, we suggest CATestBundle.

Bundle name [CATestBundle]:

Bundles are usually generated into the src/ directory. Unless you're
doing something custom, hit enter to keep this default!

Target Directory [src/]:

What format do you want to use for your generated configuration?

Configuration format (annotation, yml, xml, php) [xml]: yml

  Bundle generation

> Generating a sample bundle skeleton into app/../src/CA/TestBundle
  created .\app/../src/CA/TestBundle/
  created .\app/../src/CA/TestBundle/CATestBundle.php
  created .\app/../src/CA/TestBundle/DependencyInjection/
  created .\app/../src/CA/TestBundle/DependencyInjection/CATestExtension.php
  created .\app/../src/CA/TestBundle/DependencyInjection/Configuration.php
  created .\app/../src/CA/TestBundle/Controller/
  created .\app/../src/CA/TestBundle/Controller/DefaultController.php
  created .\app/../src/CA/TestBundle/Tests/Controller/
  created .\app/../src/CA/TestBundle/Tests/Controller/DefaultControllerTest.php
  created .\app/../src/CA/TestBundle/Resources/views/Default/
  created .\app/../src/CA/TestBundle/Resources/views/Default/index.html.twig
  created .\app/../src/CA/TestBundle/Resources/config/
  created .\app/../src/CA/TestBundle/Resources/config/services.yml
  created .\app/../src/CA/TestBundle/Resources/config/routing.yml
> Checking that the bundle is autoloaded
FAILED
> Enabling the bundle inside app\AppKernel.php
  updated .\app\AppKernel.php
OK
> Importing the bundle's routes from the app\config\routing.yml file
  updated .\app/config/routing.yml
OK

  The command was not able to configure everything automatically.
  You'll need to make the following changes manually.

- Edit the composer.json file and register the bundle
  namespace in the "autoload" section:

**Comment by Pierstoval** [comment]
What's the problem here exactly? What you posted is just the output of the command 😕

**Comment by AlexandreSad** [comment]
First there is the line :"Checking that the bundle is autoloaded FAILED" is that normal ?
Then the line: "The command was not able to configure everything automatically.You'll need to make the following changes manually.
- Edit the composer.json file and register the bundle
namespace in the "autoload" section:
But what am I really supposed to do ?

**Comment by hacfi** [comment]
May this is an issue:

```
Use / instead of \ for the namespace delimiter to avoid any problems.

Bundle namespace: CA\TestBundle
```

You need to enter `CA/TestBundle` instead.

**Comment by hacfi** [comment]
Open your `composer.json` (https://github.com/symfony/symfony-standard/blob/3.4/composer.json#L8) and add a second `psr-4` autoloading entry for you CA namespace:
```json
{
...
    "autoload": {
        "psr-4": {
            "AppBundle\\": "src/AppBundle",
            "CA\\": "src/CA"
        },
        "classmap": [ "app/AppKernel.php", "app/AppCache.php" ]
    },
...
}
```

then run `composer dump-autoload` to use the updated autoloading settings.
