### ISSUE TITLE
i got issue in installation of cakephp framework.

### ISSUE THREAD

**Issue by tajindersinghwis** [symfony/symfony-standard#1144]
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - cakephp/cakephp 3.8.1 requires ext-intl * -> the requested PHP extension intl is missing from your system.
    - cakephp/cakephp 3.8.0 requires ext-intl * -> the requested PHP extension intl is missing from your system.
    - Installation request for cakephp/cakephp 3.8.* -> satisfiable by cakephp/cakephp[3.8.0, 3.8.1].

**Comment by fabpot** [comment]
Looks like you reported your problem on the wrong repo. This is Symfony here, not CakePHP :)
