### ISSUE TITLE
The command "php bin/console generate:bundle" does not work

### ISSUE THREAD

**Issue by GandoEsprit** [symfony/symfony-standard#1145]
Hello, I have a proble with symfony when creating the bundle. When I type the command "php bin/console generate:bundle" I get this message <<There are no commands defined in the "generate" namespace>>

some one can help me please?

**Comment by xabbuh** [comment]
I am sorry, but I have to close your issue as we use GitHub issues only to discuss new features and for bug reports. For support, please refer to one of the [support channels](https://symfony.com/support). Thank you for understanding.

**Comment by hacfi** [comment]
@GandoEsprit Just a quick comment if you still need help: the command requires the composer package `sensio/generator-bundle`. Id you have a Symfony 3 project you can run `composer require sensio/generator-bundle`, enable the bundle and the command should be available. However, this package is not updated anymore and will not work with Symfony 4 or 5. If you're working with Symfony 4 or 5 you might not even need a bundle for your code anymore.

**Comment by GandoEsprit** [comment]
Thank you so much
