### ISSUE TITLE
[DX] Improve security.yml with and without AcmeDemoBundle

### ISSUE THREAD

**Issue by weaverryan** [symfony/symfony-standard#676]
We now have 2 potential paths for users:

1) With `AcmeDemoBundle`:

I think we should add some comments in `security.yml` to try to describe a few of the different pieces. Nothing big, and they should include links. One BIG thing is that route names that are used for the `form_login` and `logout`. It's not obvious that these are route names, so they look very obtuse. Commenting that these are route names and the routes are provided by `AcmeDemoBundle` (and that they equate to `/login`, for example) would go a long way.

2) Without `AcmeDemoBundle`:

If you don't install `AcmeDemoBundle`, then your `security.yml` file is almost blank. I think we should fill in some example configuration (commented out) with some comments on what it does and how to find out more about what to do in this file. The blankness of the file I think is overwhelming.

Thanks!

**Comment by iltar** [comment]
@weaverryan Is the `AcmeDemoBundle` still up-to-date, or should it be `AppBundle` now?

**Comment by weaverryan** [comment]
@iltar Thanks for the poke. I'm actually going to close this. We're pushing to have just *one* way of installing the SE (the installer). And already, the installer has a *great* `security.yml` file. And even as we modify things going forward (I'd like to remove `AcmeDemoBundle` eventually), we'll keep it very nice. If you use `create-project` and select "no" for `AcmeDemoBundle`, then this is still valid - but that is quickly becoming an invalid way to install the SE, so I'll close this.

Thanks!
