### ISSUE TITLE
[feature / proposal] extending the Symfony requirements for an app

### ISSUE THREAD

**Issue by FredoVelcro** [symfony/symfony-standard#715]
Hello all,

In my projects, i often need external libs or other requirements.
It would be nice if all of them could be checked by the Symfony requirements script "check.php" .
Extending the SymfonyRequirements may be the right way to achieve this but i wonder if this part could be more flexible...

**Comment by jrobeson** [comment]
ping? i think this issue should be closed.

**Comment by FredoVelcro** [comment]
Ok !
