### ISSUE TITLE
Console and symfony_requirements executables are not published in bin/

### ISSUE THREAD

**Issue by elodie-nazaret** [symfony/symfony-standard#769]
Hello

I'm using the symfony 3.0 structure with symfony 2.6 standard edition.

When I try to make a composer update, I have this error : 
![error](https://cloud.githubusercontent.com/assets/8955251/5663489/e791793e-9747-11e4-89e5-858944a4a4d7.png)

I opened the `bin` directory and the `console` and `symfony_requirements` executables are not published in.

What is surprising, however, is that my colleague created the project and everything works on his computer (Mac OSX).

My composer.json :  
```json
"require": {
        "php": ">=5.3.3",
        "symfony/symfony": "2.6.*",
        "doctrine/orm": "~2.2,>=2.2.3",
        "doctrine/doctrine-bundle": "~1.2",
        "twig/extensions": "~1.0",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~3.0.12",
        "sensio/framework-extra-bundle": "~3.0",
        "incenteev/composer-parameter-handler": "~2.0"
}
```

Do you have an idea of why I don't have console and symfony_requirements ?

**Comment by Tobion** [comment]
How did you activate the symfony 3.0 directory strucuture?

**Comment by Pierstoval** [comment]
AFAIK, Symfony3 structure is not fully decided, for better BC you'd better switch to 2.x structure...

**Comment by stof** [comment]
@elodie-nazaret the console script needs to be commited in the repo. Have your colleague committed it after creating the project ?

**Comment by tristanbes** [comment]
I installed it with the environement variable. It's weird that we have to commit a file which is in `bin/*`. Isn't that the purpose of one of the step of `composer install | update` to take binaries of bundles/libraries and publish it in the right folder ?

**Comment by stof** [comment]
@tristanbes the console script is the bin of the root project. It does not come from any dependency.

And btw, this is the reason why I prefer keeping the Composer bin-dir in ``vendor/bin``, which is its default location instead of changing it to ``bin``. This avoids mixing the bins of my dependencies with the bins of the root project itself.

**Comment by fabpot** [comment]
see symfony/symfony-standard#772
