### ISSUE TITLE
composer.lock

### ISSUE THREAD

**Issue by dzuelke** [symfony/symfony-standard#775]
This repo should have a `composer.lock`, as it's essentially a ready to deploy example/skeleton application.

It would also prevent the problem where installing and deploying it works fine for a few weeks until some combination of dependency versions suddenly breaks things (e.g. the doctrine/DoctrineBundle#351 mess).

With each new release of Symfony, a `composer update`, full test run, and accompanying tag, would then ensure stability.

**Comment by WouterJ** [comment]
The SE first provided a `composer.lock`, but IIRC it was removed as it didn't support the Intl/Icu components (as their version depends on your system).

**Comment by xabbuh** [comment]
@WouterJ If that was the case then, this should [no longer be a problem](http://symfony.com/blog/new-in-symfony-2-6-farewell-to-icu-component), right?

**Comment by WouterJ** [comment]
See https://github.com/symfony/symfony-standard/commit/58ae85a406409b86a313de22d17d706e5a8823b2

**Comment by dzuelke** [comment]
Yeah this is solved now.

IMO, even back then, the solution should have been to have a `composer.lock` without the ICU version that requires `ext-intl` in it, to have a lowest common denominator.

It's a lot more important for this project to work out of the box after a `composer install` than for stuff like this to be optimized out of the gate. It's intended to get as many people started quickly, not to be a fully optimized final version of a project.

People can (and will have to) always run `composer update` at some point very soon after they start developing, but the first step is to flatten the learning curve.

**Comment by WouterJ** [comment]
@dzuelke there is a `symfony new xxx` command. This downloads the archieve, which already has working vendors installed. So there should be no issue for beginners.

**Comment by dzuelke** [comment]
For that you need the `symfony` command installed.

To get going with a working version of `symfony-standard`, you should have to do the following:

1. `git clone https://github.com/symfony/symfony-standard`
1. `composer install`
1. done

**Comment by WouterJ** [comment]
The symfony installer has become the official command to install the standard edition.

Btw, I won't use git clone to get the edition. Either use composer create-project or the installer.

**Comment by dzuelke** [comment]
That is entirely beside the point. Even with the installer or `composer create-project`, an install suddenly started failing a few weeks ago because there is no `composer.lock` and `doctrine/dbal` 2.5 started getting installed which errors out during `clearCache` in the `prod` environment.

**Comment by xabbuh** [comment]
@dzuelke I'm not convinced that a `composer.lock` file fixes that issue. I'd expect to run `composer update` soon after they have installed Symfony (for whatever reason). Avoiding such error in the way @stof suggested in https://github.com/symfony/symfony-standard/pull/774#issuecomment-70650597 seems more promising to me.

**Comment by dzuelke** [comment]
Of course if fixes that issue, @xabbuh. Yes, people can, should and will run `composer update` at some later point if they start working on an actual project, but if they `composer create-project` and it's immediately broken then that's bad.

In #774, @stof gives a solution for that *specific* bug. A similar thing could (and will, just a matter of time) happen with any of the many other dependencies (and their dependencies, and their dependencies).

This is the whole reason why `composer.lock` exists in the first place.

**Comment by WouterJ** [comment]
> Even with the installer or composer create-project, an install suddenly started failing a few weeks ago because there is no composer.lock

The installer has all vendor code already included in it. So no composer action is run at all. At yes, maybe these vendors could be incompatible versions (don't know the code of the Symfony built script). However, this will be the same as the `composer.lock`, as long as the `composer.json` allows Doctrine 2.5, the `composer.lock` for a release supports it as well.

**Comment by dzuelke** [comment]
> The installer has all vendor code already included in it.

That makes it even worse. It means there is no easy way of re-building a release with the exact same set of dependencies at a later time, and it also means that the included vendor versions are not even properly recorded anywhere (like in the lockfile).

> However, this will be the same as the composer.lock, as long as the composer.json allows Doctrine 2.5, the composer.lock for a release includes it as well.

If symfony/symfony-standard has tagged releases that coincide with Symfony releases. If at the release of 2.6.1 the lock file had been re-generated (or just left alone), doctrine/dbal would have been frozen to 2.4.3, and to this day, a `composer create-project ... 2.6.1` would work just fine.

Instead, 2.6.1 worked for exactly *one* day until doctrine/dbal 2.5.0 was released, and then started breaking. That's not something you can set up CI tests for unless you want to run them every minute or whatever to guard against a changing dependency landscape.

The 2.6.3 tag is broken, and you're right that that would have happened with a `composer update`, but that breakage would have been detectable through CI tests with `SYMFONY_ENV=prod`, and in that hypothetical case, not running `composer update` would have left the lock file intact with doctrine/dbal 2.4.3 and all would be mellow.

**Comment by weaverryan** [comment]
Hey David!

Your points make sense to me actually - especially the point where a tagged standard edition can suddenly start breaking if one of the vendors muck something up.

The `composer.lock` was removed at sha: 58ae85a406409b86a313de22d17d706e5a8823b2, but @fabpot  had previously supported it (see #330).

For me, I think it makes sense to have it, because I don't see the downside (other than that there may be extra overhead when preparing an SE tag).

I hope this spurs conversation one way or another.

Thanks for the attention David :)

**Comment by dzuelke** [comment]
Thanks @weaverryan! @fabpot do you want a pull request for this?

**Comment by cordoval** [comment]
should each branch need one though?

**Comment by dzuelke** [comment]
Yeah; I think the different branches have different version selectors for some dependencies, no?

Updating the vendors before every tag would be a nice to have, but it's not strictly necessary unless things are buggy or have stopped working due to a local change (which should be rare).

**Comment by weaverryan** [comment]
@dzuelke Let's start with 1 PR agains the 2.3 branch only. Once we have a real PR to look at, I think it will solicit a real :+1:  or :-1: from the people that matter. I imagine Fabien *does* have some opinions on this.

Thanks :)

**Comment by cordoval** [comment]
i thought the tool to install symfony quickly could actually just add the composer.lock to when the downloaded was requested, that way there wouldn't be need to lock every branch since it looks like a waste of time and automation.

**Comment by weaverryan** [comment]
@cordoval You're totally right, and that will be the recommended way of installing this. But if you clone it directly, you won't have the lock file. But you're right that there is a question of "is it worth adding a .lock file here if you get it anyways if you use the recommended way of installing this library"? Of course, from a purist standpoint, yes you should, but from a practical standpoint, maybe not.

**Comment by WouterJ** [comment]
I don't think it's needed.

A lock file is more of a thing that's usefull for beginners. For people that are known to Symfony, they'll be able to fix problems in split seconds (and I think most of us already add some dependencies before we even fire up a server for the app).

For beginners, there already is the symfony installer which has a great way of solving this. Again, I'm not sure about the built process of the achives, but if it's not already there, I think we need to execute the SE tests before it to check if the dependencies packed in the achieve are not breaking anything.

**Comment by stof** [comment]
Thus, the lock file itself will not help much here: as soon as you will add another dependency in your project, you will change the lock file anyway.

**Comment by dzuelke** [comment]
> A lock file is more of a thing that's usefull for beginners. For people that are known to Symfony, they'll be able to fix problems in split seconds (and I think most of us already add some dependencies before we even fire up a server for the app).

Great, let's make it hard for beginners by having them run into weird problems they can't get to the bottom of...

I keep getting tickets from confused users about this. The docs work fine for a few days, then there's some sort of breakage in Doctrine DBAL or whereever, and stuff just suddenly breaks and the average beginner has no clue where to even start looking (it even took me a while to narrow it down to a change in DBAL 2.5).

A lock file is a good best practice and should be there from the beginning to encourage users to follow it.

Besides that, the fact that it right now is impossible for anyone to re-generate the archive (with the exact same vendors) the installer uses because the lock file is missing should be reason enough.

> Thus, the lock file itself will not help much here: as soon as you will add another dependency in your project, you will change the lock file anyway.

Yes, and then stuff will break, but for a beginner who is just poking around, it's helpful. Plus you can always go back in your SCM history to restore the working vendor versions (and potentially also figure out what happened this way).

**Comment by Pierstoval** [comment]
The beginners do not often use any SCM, so relying on this kind of restoration is more relevant for Symfony "knowers".
It's the same issue for IDEs, I know MANY Symfony developers that still use SublimeText and not at its best capacity, so you know...

**Comment by stof** [comment]
@dzuelke a lock file will not help beginners for this particular issue, because this will not prevent them to get a newer version of DBAL soon after creating their project if they run ``composer update``.

Thus, even if we provide a lock file, it would make sense to ship the current stable version of DBAL rather than shipping the older one. this is why I'm in favor of including a ``server_version`` configuration in the SE config for now rather than trying to prevent users from using DBAL 2.5

**Comment by dzuelke** [comment]
> The beginners do not often use any SCM, so relying on this kind of restoration is more relevant for Symfony "knowers".

How is that an argument *against* it?

> @dzuelke a lock file will not help beginners for this particular issue, because this will not prevent them to get a newer version of DBAL soon after creating their project if they run `composer update`.

That's true, but at least then it's a case of

1. app works
2. `composer update`
3. app is broken

versus the current "broken out of the box".

And yeah, obviously the DBAL issue needs separate addressing, but the same thing will inevitably happen with another dependency at some point :)

**Comment by fabpot** [comment]
I'm going to reintroduce the `composer.lock` file for the next releases of Symfony 2.3+.
