### ISSUE TITLE
php app/console server:stop doesn't work

### ISSUE THREAD

**Issue by samsonasik** [symfony/symfony-standard#780]
I have server running : 
```
$ php app/console server:run
Server running on http://127.0.0.1:8000
```
and try to stop with <code>php app/console server:stop</code> and got : 
```
$ php app/console server:stop
No web server is listening on http://127.0.0.1:8000
```

**Comment by xabbuh** [comment]
The web server that is started by the `server:run` command is terminated once you stop the `server:run` command. So there is nothing to stop using `server:stop`. You can use the `server:start` command instead to run completely run the web server in the background.

**Comment by samsonasik** [comment]
oh, yes, you're right. thank you. i'm closing ;)
