### ISSUE TITLE
composer.lock in the repository

### ISSUE THREAD

**Issue by clementlyon** [symfony/symfony-standard#783]
Is it normal that the composer.lock file is present in the repository ?

When installing a fresh 2.7.x-dev project the message is : 

Warning: The lock file is not up to date with the latest changes in composer.json. You may be getting outdated dependencies. Run update to update them.

And i have a 2.6.4 project at the end of the installation...

**Comment by Tobion** [comment]
Yes it's intended. But apparently @fabpot needs to recreate the lock file.

**Comment by fabpot** [comment]
fixed now.
