### ISSUE TITLE
Using 'app/autoload.php' instead of 'app/bootstrap.php.cache' in app_dev.php by defaults

### ISSUE THREAD

**Issue by zomberg** [symfony/symfony-standard#788]
Symfony's documentation has a great article http://symfony.com/doc/current/cookbook/debugging.html.
Using 'app/autoload.php' instead of 'app/bootstrap.php.cache' in app_dev.php is really help with debug application.

When I go with debugger into 'bootstrap.php.cache' the debugging become more complicated.

On my work and my personal projects I always disable bootstrap.php.cache.
All my colleagues which used Symfony 2 also pointed that started new projects with disabling bootstrap.php.cache and enable app/autoload.php instead.
I see that this approach also used in https://github.com/gimler/symfony-rest-edition, which promoted on http://symfony.com/distributions page.

What you think about using app/autoload.php by default in app_dev.php?

**Comment by weaverryan** [comment]
Hey @zomberg!

The big reason against this will be that Fabien has always wanted the different environments to have as little difference as possible, to avoid issues that happen in one, but not the other. And I *do* think that's important. Of course, we *do* promote exactly what you're saying here in the docs: http://symfony.com/doc/current/cookbook/debugging.html.

One idea I can think of is including the require line for `app/autoload.php` in `app_dev.php`, but commented out, and with 1 commented line explaining how you can improve debugging.

Cheers!

**Comment by zomberg** [comment]
Hi Ryan!

Ok, I undestand your point of view.

I think it is good idea to include in this code in comments with link to http://symfony.com/doc/current/cookbook/debugging.html page.

Thanks.

**Comment by weaverryan** [comment]
:+1: to including it in the code with comments!

**Comment by jrobeson** [comment]
alternatively.. we could pull the autoloader out of the bootstrap.php.cache file  so then you simply comment include 'bootstrap.php.cache'; if you don't want the cache.

**Comment by Tobion** [comment]
@jrobeson this sounds like a good plan both from a usuability and from an architecture perspective as there is not reason to mix the bootstrap with the already existring autoload.php file.

**Comment by stof** [comment]
looks like a good idea indeed (we should still keep it in bootstrap.php.cache for now for BC reasons though)

**Comment by sstok** [comment]
I actually solved this with a condition for the app file (using Sf3 directory structure btw).
And for the PHPUnit I don't use the bootstrap.php.cache but rather the autoloader directly.

```
// Don't use the class caches when xdebug is enabled
// so its easier to debug errors.
$loadClassCache = !isset($_COOKIE['XDEBUG_SESSION']);
if ($loadClassCache) {
    $loader = require_once __DIR__.'/../var/bootstrap.php.cache';
} else {
    $loader = require_once __DIR__.'/../app/autoload.php';
}
```

**Comment by cordoval** [comment]
it should be:

```php
// Don't use the cached classes when ...
```
Someone can try to debug without xdebug though no? I wonder if doing APP_ENV === 'dev' or just explicitly setting and testing $debug on the condition is better. This will make the endpoints very similar yet accomplish what you are saying here.

**Comment by sstok** [comment]
Its actually a bit more then just this snippet, but it gives you the idea :)

Full details:
https://github.com/park-manager/parkmanager/blob/master/web/index.php#L18
https://github.com/park-manager/parkmanager/blob/master/src/Core/EntryPoints/Http/Application.php#L78

**Comment by cordoval** [comment]
yep :older_man:
