### ISSUE TITLE
problem

### ISSUE THREAD

**Issue by hanounna** [symfony/symfony-standard#795]
php.exe "C:\Program Files (x86)\EasyPHP-DevServer-14.1VC9\data\localweb\hanounna2.6\app\console" doctrine:schema:update --force
Nothing to update - your database is already in sync with the current entity metadata.

**Comment by cordoval** [comment]
this ticket is in no way descriptive and notice is not an error!

**Comment by hanounna** [comment]
je suis dans la phase d’intégration du FOSUserBundle  quand je fait php app/console doctrine:schema:update --force
la resultat est : Nothing to update - your database is already in sync with the current entity metadata.
et la base est vide

**Comment by cordoval** [comment]
se il vous plaît le signaler si des problèmes dans FOSUserBundle mais je ne vois pas le rapport à symfony.

**Comment by hanounna** [comment]
j'ai aucun probleme dans FOSUserBundle 
j'ai creer le bundle UserBundle et l entity User extends  BaseUser

**Comment by Tobion** [comment]
Please ask support questions on the mailing list. http://symfony.com/fr/mailing-lists
