### ISSUE TITLE
Should we not ramp Doctrine's default version to 2.5 in composer.json for the 3.0 release?

### ISSUE THREAD

**Issue by naroga** [symfony/symfony-standard#797]
Doctrine 2.5 has just been released, and Symfony is still using <2.5 in composer.json. 2.5 breaks BC with 2.4- projects, so if we can't ramp it up in the 3.0 release, we won't be able to do so until 4.0, I think. Which means eventually we'll be using a deprecated version of doctrine as the default orm of the 3.x branch.

I started this discussion in the wrong repository, got redirected here. I'll fix this myself if people agree on upgrading the default ORM version.

**Comment by Tobion** [comment]
This is just the standard edition that brings along the default composer.json. We don't need to keep BC here as the composer.json is not auto updated but has to manually be updated by users...

**Comment by Tobion** [comment]
Closing as this has nothing to do with 3.0 and we can change the default doctrine version whenever we see fit.

**Comment by gnugat** [comment]
I think the question is still relevant: since we don't have to wait until version 3.0, can we update doctrine's version now?

**Comment by fabpot** [comment]
Are we talking about DBAL or ORM? Because we know that we cannot upgrade to the 2.5 version of the DBAL.

**Comment by Tobion** [comment]
Sure if the original problem why we forced < 2.5 is really solved.

**Comment by naroga** [comment]
@fabpot, I was thinking about upgrading the ORM default version. I'm worried we'll launch the skeleton app in 3.0 with `composer.json` referencing the previous version (2.4), and won't be able to upgrade the default version later on, due to BC breaks that happened in 2.5. Soon, every new Symfony skeleton app would be installed with a deprecated version of Doctrine ORM.

**Comment by naroga** [comment]
@fabpot, @Tobion, what's the issue with DBAL 2.5? Is it https://github.com/doctrine/DoctrineBundle/issues/351? Separate discussion, but it got me curious.

**Comment by xabbuh** [comment]
@naroga yes (well, in fact http://www.doctrine-project.org/jira/browse/DBAL-1057)
