### ISSUE TITLE
intl.error_level must be 0

### ISSUE THREAD

**Issue by dosten** [symfony/symfony-standard#801]
As seen in symfony/symfony#14430, if the `intl.error_level` option is set to a value other than 0, the `Intl` extension will return a warning or an error. Maybe we can add this as a requirement or a recommendation in the `SymfonyRequirements.php` file. What do you think?

**Comment by dosten** [comment]
Some feedback about this?

**Comment by Tobion** [comment]
The requirements are part of the sesion distribution bundle. Please open in that repo.
