### ISSUE TITLE
Class Sensio\Bundle\DistributionBundle\Composer\ScriptHandler is not autoloadable, can not call post-update-cmd script

### ISSUE THREAD

**Issue by heyalbert** [symfony/symfony-standard#807]
try to composer update
```
Writing lock file
Generating autoload files
Class Incenteev\ParameterHandler\ScriptHandler is not autoloadable, can not call post-update-cmd script
Class Sensio\Bundle\DistributionBundle\Composer\ScriptHandler is not autoloadable, can not call post-update-cmd script
Class Sensio\Bundle\DistributionBundle\Composer\ScriptHandler is not autoloadable, can not call post-update-cmd script
Class Sensio\Bundle\DistributionBundle\Composer\ScriptHandler is not autoloadable, can not call post-update-cmd script
Class Sensio\Bundle\DistributionBundle\Composer\ScriptHandler is not autoloadable, can not call post-update-cmd script
Class Sensio\Bundle\DistributionBundle\Composer\ScriptHandler is not autoloadable, can not call post-update-cmd script
Class Sensio\Bundle\DistributionBundle\Composer\ScriptHandler is not autoloadable, can not call post-update-cmd script
```

**Comment by WouterJ** [comment]
Do you still have `sensio/distribution-bundle` in your requirements?

**Comment by heyalbert** [comment]
Found the bug - a misconfiguration in my composer.json.

**Comment by Webonaute** [comment]
@heyalbert its very frustrating when we search for same issue and ppl close ticket just saying I fix the error without actually say what it was so other ppl can profite of the fix.

**Comment by NeoVG** [comment]
Damnit! WHAT misconfiguration? :D

**Comment by stefanius** [comment]
Got the same issue.

**Comment by ChadSikorra** [comment]
What worked for me was to completely blow away the vendors folder `rm -rf ./vendor` then run a `composer update`.

**Comment by robertfausk** [comment]
Got the same issue. Try to add SensioDistributionBundle if not already added by executing:

```
composer require sensio/distribution-bundle
```

**Comment by Nyholm** [comment]
Sorry for also posting in this thread. But it is a top result on Google when searching for this error. 

###To solve this: 
Make sure you require both `sensio/distribution-bundle` and `incenteev/composer-parameter-handler`. Then make sure your composer.json looks similar to [Symfony standard's](https://github.com/symfony/symfony-standard/blob/3.2/composer.json). Look at the `autoload`, `extra` and the `script` section.

**Comment by ajaysSymfonyExpert** [comment]
got same issue during upgrade symfony3.4 to  v4.4 what should i do ?
