### ISSUE TITLE
Update link in README

### ISSUE THREAD

**Issue by bdeanindy** [symfony/symfony-standard#808]
The link to is returning a 404, but with links to alternate versions:
Link Display: SensioGeneratorBundle (in dev/test env) - Adds code generation capabilities
URL: http://symfony.com/doc/2.7/bundles/SensioGeneratorBundle/index.html

**Comment by Pierstoval** [comment]
This is a [symfony-docs](https://github.com/symfony/symfony-docs) issue, not symfony-standard.

**Comment by WouterJ** [comment]
@Pierstoval it is an issue with symfony-standard. The link in the README file of this repository has to be updated. Since some months, bundle docs are rendered seperately with their own versions (no longer the Symfony versions). So it probably has to be 1.something or so instead of 2.7

**Comment by xabbuh** [comment]
see #809
