### ISSUE TITLE
Unused statements and comments in app.php

### ISSUE THREAD

**Issue by kristofvc** [symfony/symfony-standard#812]
In web/app.php there's an unused use-statement to include the ApcClassLoader. The code that uses this statement is commented. One option to avoid the unused statement would be to also comment it though both this statement and the comment give warnings on Sensiolabs Insight. 

I would prefer both the statement and the comment get removed in app.php, and the use of the ApcClassLoader (if not yet) gets documented.

If this is something all agree on, I'd be happy to change it.

**Comment by Pierstoval** [comment]
I think it's best for you to just modify your SensioLabs Insight configuration to ignore `web/app.php` and `web/app_dev.php` files.

**Comment by kristofvc** [comment]
@Pierstoval This is indeed how I would circumvent the issue, though the unused statement remains.

**Comment by xabbuh** [comment]
I would comment the `use` statement. Everything else related to the `ApcCache` is commented too.

**Comment by weaverryan** [comment]
I'm not sure how often the `ApcClassLoader` is used - I've personally never used it, `composer dump-autoload --optimize` gets you *most* of the performance gain that this gives you. I would support removing it.

This is already documented in the performance chapter, but if we removed it from `app.php`, that little section would need to be updated (it refers to the code already being in the file).

**Comment by Pierstoval** [comment]
Is APC still supported in PHP 5.5+ ?

**Comment by ogizanagi** [comment]
@Pierstoval : APC user cache is still available as the APCu packages.

**Comment by fabpot** [comment]
Closing as the comments help people activate the APC cache loader.
