### ISSUE TITLE
PDOSession Handler sess_lifetime vs cookie_lifetime

### ISSUE THREAD

**Issue by stevenmusumeche** [symfony/symfony-standard#817]
I've got Symfony setup to store sessions in a database.  I have my session cookies configured to last for 30 days.  

```
framework:
    session:
        handler_id:  session.handler.pdo
        cookie_lifetime: 2592000 # 30 days
services:
    session.handler.pdo:
        class:     Symfony\Component\HttpFoundation\Session\Storage\Handler\PdoSessionHandler
        public:    false
        arguments:
            - "mysql:host=%database_host%;port=3306;dbname=%database_name%"
            - { db_username: %database_user%, db_password: %database_password% , db_table: symfony_sessions, lock_mode: 1 }
```

The session cookie expiration is being set correctly, however, the sess_lifetime value stored in the database is always `1440`.  How are these two values related? Shouldn't the `sess_lifetime` value be equal to the `cookie_lifetime` value?

**Comment by Tobion** [comment]
These are different lifetimes. One is for the cookie and one for GC. Please have a look at php session documentation.

**Comment by Tobion** [comment]
Is the cookie lifetime also extended on each request? Maybe it makes sense to adjust the gc lifetime default automatically by cookie lifetime since gc_lifetime < cookie_lifetime probably makes no sense.

But this issue is in the wrong repo anyway. Please reopen if needed on symfony/symfony.
