### ISSUE TITLE
2.7.0 archive not up-to-date

### ISSUE THREAD

**Issue by xabbuh** [symfony/symfony-standard#820]
The generated archive [published on symfony.com](http://get.symfony.com/Symfony_Standard_Vendors_2.7.0.tgz) is not up-to-date. For example, the version constraint for the `symfony/symfony` package is `~2.7@beta` (i.e. the fix from #814) is not reflected in the archive.

@fabpot Is it possible to get an update for the archive? People complain about this when using the Symfony Installer.

**Comment by weaverryan** [comment]
I think we just need a new tag - iirc, we forgot to update composer.json before 2.7.0

**Comment by xabbuh** [comment]
Indeed, that's the case.

**Comment by stof** [comment]
#814 was merged after the tag, so the archive is totally uptodate. and btw, ``~2.7@beta`` will still resolve to 2.7.0 currently in composer as we don't have any newer beta release

**Comment by Tobion** [comment]
So why not closing this issue then?

**Comment by xabbuh** [comment]
We will have to live with the fact that you get the second Symfony 2.7 beta when using the Installer and update dependencies manually for now.

**Comment by GrahamCampbell** [comment]
Why would that be the case? `@beta` is just a **minimum**. The stable version is always preferred by composer.

**Comment by xabbuh** [comment]
@GrahamCampbell The installer doesn't execute Composer at all. It just downloads the pre-built archive and extracts it.

**Comment by GrahamCampbell** [comment]
Ok, right. :(
