### ISSUE TITLE
composer.json : symfony-standard and symfony require different PHP versions

### ISSUE THREAD

**Issue by alexislefebvre** [symfony/symfony-standard#821]
`symfony-standard` requires [PHP `>=5.3.3`](https://github.com/symfony/symfony-standard/blob/2.7/composer.json#L10) while `symfony` requires [PHP `>=5.3.9`](https://github.com/symfony/symfony/blob/2.7/composer.json#L19).

I don't know if it's a problem or not. Does it mean that with PHP 5.3.6 (randomly taken as an example) you can install `symfony-standard` but not `symfony` which is required?

(source : [Dani Sancas](http://stackoverflow.com/questions/30570276/symfony2-lts-how-to-upgrade-from-2-3-to-2-7/30572402#comment49543670_30572402))

**Comment by fabpot** [comment]
fixed in 34eaf2f
