### ISSUE TITLE
Wrong Symfony dependency version

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-standard#822]
When you install Symfony with this command:

```bash
$ symfony new my_project
```

If you open the `composer.json` file of the installed project, you'll find the following:

```json
    "require": {
        "php": ">=5.3.3",
        "symfony/symfony": "~2.7@beta",  <-- THIS IS THE PROBLEM
        "doctrine/orm": "~2.2,>=2.2.3,<2.5",
        "doctrine/dbal": "<2.5",
        "doctrine/doctrine-bundle": "~1.4",
        "symfony/assetic-bundle": "~2.3",
        "symfony/swiftmailer-bundle": "~2.3",
        "symfony/monolog-bundle": "~2.4",
        "sensio/distribution-bundle": "~3.0,>=3.0.12",
        "sensio/framework-extra-bundle": "~3.0,>=3.0.2",
        "incenteev/composer-parameter-handler": "~2.0"
    },
```

When you install Symfony without specifying a version, the installer uses the `latest` special version and it downloads the `http://symfony.com/download?v=Symfony_Standard_Vendors_latest.zip` file. If you try to download that file yourself and uncompress it, you'll find that the `~2.7@beta` constraint is defined in the `composer.json` file.

How should we fix this issue?

**Comment by Pierstoval** [comment]
It comes from the symfony standard repo, so I guess that the next version might fix this.
I think it's too dangerous to replace something like this manually...

**Comment by ogizanagi** [comment]
I think it's the same issue as in #820 ?

**Comment by javiereguiluz** [comment]
@ogizanagi indeed it's the same issue! I'm sorry :(  However, I don't understand why that issue was closed without doing anything about it.

**Comment by ogizanagi** [comment]
Because as @stof said:

> ~2.7@beta will still resolve to 2.7.0 currently in composer as we don't have any newer beta release

**Comment by javiereguiluz** [comment]
Yes, but that's not *"the Symfony way of doing things"*. If 2.7.0 is not a beta anymore, its constraint shouldn't be `@beta`.

**Comment by xabbuh** [comment]
Unfortunately, any change made to the file will only be available with the next release (Git tag). It was forgotten to make the change before the stable release. So, now we have to wait for 2.7.1.

**Comment by Pierstoval** [comment]
Don't worry @javiereguiluz , actually, composer will rely only on 2.7.0 as @stof said, and when 2.7.1 will be released, the problem will be solved.
 
It impacts both composer, the symfony installer, and the strange people that download the repo as zip :)

**Comment by javiereguiluz** [comment]
@xabbuh sure, I don't mind waiting. I think that's the best solution :)

So I'm closing this issue because it's going to be fixed soon. Thanks.

**Comment by stof** [comment]
@javiereguiluz and the fix has already been done in the repo btw. It is just not released yet

**Comment by javiereguiluz** [comment]
@stof great! Thank you.

By the way, could we get rid of the AcmeDemoBundle in the next Symfony releases? That could happen if you could review these PR:

  * https://github.com/symfony/symfony-standard/pull/818
  * https://github.com/symfony/symfony-standard/pull/819
  * https://github.com/sensiolabs/SensioDistributionBundle/pull/212

Thanks!

**Comment by Tobion** [comment]
I reviewed all.

**Comment by javiereguiluz** [comment]
@Tobion thank you!
