### ISSUE TITLE
The downloaded package does not include PHPUnit by default.

### ISSUE THREAD

**Issue by SvenRtbg** [symfony/symfony-standard#823]
Downloading the standard edition either via Symfony installer or `composer create-project` does create a demo test, but does not install PHPUnit as dependency to execute it.

Suggestion: Add PHPUnit to the dev dependencies of this package.

**Comment by stof** [comment]
We tend to prefer global installation of PHPUnit (through the phar or a global composer install, but I recommend the PHAR) in Symfony projects. This is why the standard edition does not depend on phpunit.

**Comment by GrahamCampbell** [comment]
I agree with @stof. PHPUnit should NOT be bundled with symfony by default.
