### ISSUE TITLE
doctrine 2.4 and yaml 2.7 deprecated calls

### ISSUE THREAD

**Issue by allardmuis** [symfony/symfony-standard#825]
Hi guys!

When moving from Symfony 2.3 to Symfony 2.7 I encountered a problem with deprecated calls in Doctrine. Symfony-standard requires Doctrine 2.4 ("doctrine/orm": "~2.2,>=2.2.3,<2.5") which performs deprecated calls to the Symfony Yaml component in the YamlDriver.

This is fixed in Doctrine 2.5, and deprecated calls are not a problem per se. But I wonder how this is handled in Symfony 3.0, is the dependency to Doctrine changed to 2.5?

**Comment by Tobion** [comment]
There is not a hard dependency on doctrine <2.5. This is just a workaround for #748. You can either use the latest 2.5 or the dev version of 2.4 which have the problem fixed. Or you specify the RDBMS version manually as explained in the tickets, in which case you can use any doctrine version.
So you are not forced the use 2.4, this is just the default recommendation.
