### ISSUE TITLE
doctrine:generate:crud command create setDefaultOptions() method instead of configureOptions() method in form class

### ISSUE THREAD

**Issue by mzmgh** [symfony/symfony-standard#827]
As you now setDefaultOptions() method was introduced in Symfony 2.7. Previously, the method was called setDefaultOptions() but when I use doctrine:generate:crud command it create setDefaultOptions() method instead of configureOptions() method.

**Comment by stof** [comment]
``doctrine:generate:crud`` is part of SensioGeneratorBundle. Please open an issue on this bundle

**Comment by mzmgh** [comment]
Oh i'm sorry. thanks for your remind.
