### ISSUE TITLE
Overriding the default error templates not working as documented

### ISSUE THREAD

**Issue by EduardoLeggiero** [symfony/symfony-standard#831]
I am using Symfony 2.7 in a new fresh project and I have a problem when trying to override the default error template.

According with documentation http://symfony.com/doc/2.7/cookbook/controller/error_pages.html#use-default-exception-controller: "(...) the following logic to determine the template filename:

1) Look for a template for the given format and status code (like error404.html.twig);
2) If the previous template doesn't exist, discard the status code and look for a generic template for the given format (like error.html.twig);
3) If none of the previous template exist, fall back to the generic HTML template (error.html.twig).

If I create a file error404.html.twig, the page works fine and I can see the error page with the custom layout when call a not found resource (or through the /_error/404 dev route).

But, If I create only the error.html.twig to try to override all the error pages (like 404, 403 and 500) using only a single template, the file is ignored and I see the default error page from the template of the TwigBundle. (for example when try to get a not found resource or either through the /_error/404 route)

Could anyone try to test if this is an issue?

Thanks!

Eduardo

**Comment by xabbuh** [comment]
Where did you place your custom error template?

**Comment by EduardoLeggiero** [comment]
I put it in app/Resources/TwigBundle/views/Exception.

**Comment by xabbuh** [comment]
Did you try to view the page with the debug mode enabled or disabled (when the debug mode is enabled, the controller is not looking for the `error*` templates, but tries to load `exception*` templates, see https://github.com/symfony/symfony/blob/2.7/src/Symfony/Bundle/TwigBundle/Controller/ExceptionController.php#L103-120)?

**Comment by stof** [comment]
And when overwriting templates, make sure to clear your cache as Twig might not deal properly with refreshing the cache when it must use a different source file than for the previous access to the template.

**Comment by weaverryan** [comment]
I'm going to close this, unless there's some more information. I haven't heard of any other issues related to this.

**Comment by ympadilha** [comment]
Hey guys, I am having the same problem, any clue?
I created a error.html.twig inside app/Resources/views/Exception ( since I don't have a TwigBundle folder )
I also tried creating a TwigBundle folder as the documentation says but I didn't get any lucky.

Any help would be quite appreciated.
Thank you!
