### ISSUE TITLE
sensio/distribution-bundle ~4.0 not compatible with PHP 5.3.3 installs

### ISSUE THREAD

**Issue by dcarbone** [symfony/symfony-standard#842]
Hey all,

The releases 2.6.10 and 2.6.11 list ` "sensio/distribution-bundle": "~4.0" ` as a requirement, however that bundle version requires PHP >= 5.3.9 while the root symfony framework requires >= 5.3.3.  I am one of the unfortunates working in RHEL-land, and am currently stuck on 5.3.3.

I am not familiar with the differences between versions 3 and 4 of the above bundle, but is it possible to backport any needed improvements from 4 into 3 to keep framework 2.6 working with it's listed requirements?  Or to simply keep using 3.0.30?

Thanks
-Daniel

**Comment by stof** [comment]
@fabpot is there anything in SensioDistributionBundle 4.0 actually requirement PHP >= 5.3.9 ?

**Comment by stof** [comment]
@dcarbone you can just use the version 3 of the bundle in your own projects btw

**Comment by dcarbone** [comment]
@stof Yeah that is what we're doing currently, just wanted to bring it to the attention of the curators.  Seems to work fine with 3.0.30.

**Comment by fabpot** [comment]
I don't think there is anything requiring 5.3.9 in 4.0 but at some point, we need to move forward. Sticking with 3.0 is probably the best option when you are stuck on PHP 5.3.3
