### ISSUE TITLE
why do i have modified files after git clone && composer install?

### ISSUE THREAD

**Issue by OskarStark** [symfony/symfony-standard#843]
![bildschirmfoto 2015-08-13 um 14 18 47](https://cloud.githubusercontent.com/assets/995707/9249572/657a320e-41c6-11e5-936b-dd25acbd2f3a.png)

shall i fix these files and provide a PR?

![bildschirmfoto 2015-08-13 um 14 21 36](https://cloud.githubusercontent.com/assets/995707/9249595/a0e99eec-41c6-11e5-8628-9b12f0b7e366.png)

![bildschirmfoto 2015-08-13 um 14 22 05](https://cloud.githubusercontent.com/assets/995707/9249612/bd84cf0e-41c6-11e5-936e-a1e1556e450e.png)
![bildschirmfoto 2015-08-13 um 14 22 18](https://cloud.githubusercontent.com/assets/995707/9249611/bd84eafc-41c6-11e5-8fc4-88b3ed715461.png)

**Comment by stof** [comment]
have you run composer install or composer update ? ``composer install`` cannot change the lock file.

**Comment by OskarStark** [comment]
you are right @stof these files are updated after composer update, sorry!

**Comment by stof** [comment]
And for update, this is expected. There is a composer script in the composer.json which updates these files automatically from the files maintained in SensioDistributionBundle, to ensure you get uptodate requirement checks. So if ``composer update`` has updated the bundle, you can receive the new version of these files.

**Comment by OskarStark** [comment]
thank you for the infos!
