### ISSUE TITLE
Console not loading class cache

### ISSUE THREAD

**Issue by liquorvicar** [symfony/symfony-standard#845]
We have been having problems recently with a Symfony app when constructor signatures for our customer services have changed and we have been unable to run cache:clear in production.

The problem seems to be that the compiled DI container (app/cache/prod/appProdProjectContainer.php) constructs the service using the old service definition but it's actually loading the new class and hence there is an error since the console is not loading the class cache.

As an example, consider a custom service like this:
```
namespace MyApp\MyBundle;

use Psr\Log\LoggerInterface;

class CustomService
{
    /**
     * @var LoggerInterface
     */
    protected $logger;
    
    /**
     * @param LoggerInterface $logger
     */
    public function __construct(LoggerInterface $logger)
    {
        $this->logger = $logger;
    }
}
```

The cached version in the container would be something like:
```
    protected function getMyApp_CustomService()
    {
        return $this->services['my_app.custom_service'] = new \MyApp\MyBundle\CustomService($this->get('logger'));
    }
```

Now say in the next feature release we add an extra dependency to the service:
```
namespace MyApp\MyBundle;

use Psr\Log\LoggerInterface;
use Doctrine\ORM\EntityManager;

class CustomService
{
    /**
     * @var LoggerInterface
     */
    protected $logger;
    /**
     * @var EntityManager
     */
    protected $em;
    
    /**
     * @param LoggerInterface $logger
     * @param EntityManager $em
     */
    public function __construct(LoggerInterface $logger, EntityManager $em)
    {
        $this->logger = $logger;
    }
}
```

Now when the service is loaded an error is thrown as there is no second parameter being passed to the constructor.

We have added `$kernel->loadClassCache();` to app/console and this seems to have resolved the issue.

So I have a few questions:
- is this change likely to cause issues elsewhere (I'm by no means an expert on Symfony internals)?
- if so, is there a better way to get round this issue?
- is this a bug? If so, I am happy to do a quick PR to fix it.

**Comment by stof** [comment]
this is always a problem. In no-debug mode, running a command when the cache exists will use the existing cache even when it is totally old.

My advice is to always clear the cache the hard way (``rm -rf app/cache/prod``) when you deploy changes instead of relying on the flawed ``cache:clear`` command.

**Comment by stof** [comment]
Adding ``$kernel->loadClassCache()`` may be fixing it in your case because the class causing you issues in the class cache, but most cases where it happens won't be solved by this.

**Comment by liquorvicar** [comment]
The problem isn't so much that the console is using the old cache, it's that it's using a cached version of the container and the current (i.e. non-cached) version of our custom service. Add our custom service to the class cache and then getting the console command to use the class cache seems to work ok.

AFAIK using cache:clear is a (nearly) seamless way of clearing the cache in prod. As I understand it, it warms a new cache before destroying the old and then just swaps them. Surely using rm -rf will leave a bigger window where the cache is missing/inconsistent/out-of-date etc?

**Comment by Pierstoval** [comment]
You can maybe use `app/console cache:clear --no-warmup` but basicly, `rm -rf app/cache/*` works better

**Comment by liquorvicar** [comment]
So basically `rm -rf app/cache/prod` then `app/console cache:warmup --env=prod`?

if `cache:clear` is so unreliable why is it still there??

**Comment by stof** [comment]
@liquorvicar most classes of the code base are *not* in the class cache, meaning there is no way to boot the kernel using only the old codebase (thus, warming up the cache with the old codebase would mean we could warm it the wrong way).

**Comment by liquorvicar** [comment]
@stof it's not so much the fact that most of the code is not in the class cache, it's the fact that the console is using the cached container but not the class cache. Thus, even if you add your customer services to the class cache to avoid the issue of old vs new code, it still breaks!

**Comment by stof** [comment]
@liquorvicar you would not want to add your whole codebase to the class cache anyway. This would make performance worse by loading lots of unnecessary things
And if you add everything to the class cache, the cache warmup could still be broken because it would warmup things with the old code.
