### ISSUE TITLE
Add information about APC

### ISSUE THREAD

**Issue by JHGitty** [symfony/symfony-standard#848]
In the Symfony Standard Edition (Symfony 2.7.x) there is an uncommented cache example in
`app/config/config_prod.yml` with APC. But APC is not available for PHP5.5+.

I think there should be more information as comment next to the examples.

```yml
#framework:
#    validation:
#        cache: validator.mapping.cache.apc
#    serializer:
#        cache: serializer.mapping.cache.apc

#doctrine:
#    orm:
#        metadata_cache_driver: apc
#        result_cache_driver: apc
#        query_cache_driver: apc
```

**Comment by ogizanagi** [comment]
APC user cache (which is used by `doctrine/cache` and is only data storage, not opcode) is still available for PHP 5.5+ as the apcu package. So I don't think there is any issue ?

**Comment by stof** [comment]
Closing as @ogizanagi is right

**Comment by JHGitty** [comment]
Maybe there should be a short official documentation about APC and a link to the documentation next to the comments as we have it on other config files?

**Comment by Pierstoval** [comment]
There is doc everywhere as long as you type `php5 apcu` in google.
