### ISSUE TITLE
The link to the installation documentation is broken

### ISSUE THREAD

**Issue by JVerstry** [symfony/symfony-standard#849]
I have noticed that the link to the installation documentation leads to a 404.

https://symfony.com/doc/2.8/book/installation.html

**Comment by stof** [comment]
@javiereguiluz this seems an issue on the website, because this page exists in the 2.8 branch of the doc repo: https://github.com/symfony/symfony-docs/blob/2.8/book/installation.rst
Can you check it ?

**Comment by javiereguiluz** [comment]
This issue is in fact a "feature". As of now, 2.8 version doesn't exist. We only publish documentation for released versions ... with the only exception of the `master` branch, which we always map to the upcoming stable version (`3.0` at the moment).

@JVerstry did you click on that link from somewhere in symfony.com or did you create it yourself?

**Comment by stof** [comment]
@javiereguiluz 2.8 is also an upcoming stable version (we have 2 upcoming stable versions currently).

And we have this link in the readme of the repo.

**Comment by javiereguiluz** [comment]
The situation of having two stable versions released at the same time is very exceptional and it's not worth it to change things (for example we didn't change the /download page tabs, we just added a message explaining the exceptional situation).

We could remove the link from the README temporarily as a solution.

**Comment by stof** [comment]
@javiereguiluz the doc team is maintaining the documentation branch for 2.8. Is it that much work to build it too ?

**Comment by stof** [comment]
and given 2.8 is the main branch of the repo, remaining the link is not a right solution IMO

**Comment by javiereguiluz** [comment]
I have a better solution than removing the link: make unstable/unreleased versions point to `master`:

https://symfony.com/doc/master/book/installation.html

**Comment by WouterJ** [comment]
This will happen a lot more in the future (each major version bump actually, if I got it right). So I think it makes sense to prepare the system for it.

Without knowing the code behind it, is it very difficult to have a 2.8 version that just exists but isn't aliased to current or master?

**Comment by JVerstry** [comment]
@javiereguiluz It is in the read.me

**Comment by Tobion** [comment]
Closing  as https://symfony.com/doc/2.8/book/installation.html is working now. If there is some release improvements for the docs necessary, please open a ticket there.
