### ISSUE TITLE
[3.0] move tests out of src folder

### ISSUE THREAD

**Issue by Tobion** [symfony/symfony-standard#855]
https://github.com/symfony/symfony-standard/pull/850#issuecomment-140676179
> Test classes could be autoloaded only in a development environment by moving them from src/AppBundle/Tests to tests and adding a autoload-dev section in composer.
What do you think about this suggestion?

**Comment by Pierstoval** [comment]
:+1: , it'd also be easier to remove the tests from the deployment engines.

**Comment by stof** [comment]
:+1: (and maybe even in 2.8 btw)

**Comment by javiereguiluz** [comment]
From a technical point of view, this is probably the best option. But keep in mind that it will break all the existing documentation, articles, blog posts, etc. And this is also one the most well-known conventions in the Symfony world, so it's a bigger change than it looks.

**Comment by weaverryan** [comment]
Is there an advantage to not having them autoloaded? The advantage I see is clarity, as `tests` at the root is nice to see. We already will need to make many changes to the docs - notably `app/console` -> `bin/console`, so if this were another change, it's not a huge deal.

+0 I don't see it as a huge win, but does include some work

**Comment by Tobion** [comment]
The advantage is that autoloading is potentially faster.

**Comment by gnugat** [comment]
Autoloading is usually one of the bottleneck in application performances, making it lighter by avoiding unnecessary classes (tests, fixtures, etc) in production environment seems reasonable.
Documentation can be updated followed by a blog post on the official symfony website should be sufficient for the switch: existing blog posts will become obosolete anyway with the new 3.0 directory tree.

> **Note**: I'm not saying that we should be careless and break everything, just that in this specific case this is reasonable.

**Comment by sstok** [comment]
:+1:

**Comment by fabpot** [comment]
anyone willing to do the PR?

**Comment by Pierstoval** [comment]
In progress in #859 if needed
