### ISSUE TITLE
Wrong in project bundle or wrong phpunit configuration for 2.3

### ISSUE THREAD

**Issue by amansilla** [symfony/symfony-standard#865]
I'm not sure about what is the default bundle for the version 2.3, since actually is `AppBundle`. For version 2.4 return to the old default bundle `Acme/DemoBundle` and from 2.5 again `AppBundle`.

I guess the default bundle name was changed by mistake on version 2.3 otherwise, I think it should be also applied to version 2.4.

In case the default bundle name for version 2.3 is right, the phpunit configuration should be fixed.

Guys, let me know yours thoughts. :smile:

**Comment by xabbuh** [comment]
The change was made at a time when Symfony 2.5 was supported, but 2.4 was not anymore. Thus, changes only got merged up from the `2.3` branch to `2.5` and higher.

**Comment by amansilla** [comment]
Ok thanks for the info @xabbuh. 

In that case my pull request https://github.com/symfony/symfony-standard/pull/866 should be applied since the test of the AppBundle aren't going to be executed, isn't?
