### ISSUE TITLE
Why is AppKernel not loaded by Composer?

### ISSUE THREAD

**Issue by mnapoli** [symfony/symfony-standard#868]
Is there a reason why the `AppKernel` file is not loaded by Composer? I.e. registered like this in `composer.json`:

```json
{
    ...
    "autoload": {
        ...
        "files": [
            "app/AppKernel.php"
        ]
    },
    ...
}
```

Since it is always loaded, letting Composer do the job would make each entry point of the application (console, app.php, app_dev.php, …) a little simpler.

**Comment by Pierstoval** [comment]
Sounds like a good idea to me :+1: , but I don't know if there are other implications to this...

**Comment by stof** [comment]
this looks good to me. It would allow to simplify places using it. they can simply assume it is autoloadable.

**Comment by Tobion** [comment]
:+1:

**Comment by mnapoli** [comment]
OK great, should the pull request be made against master or any other branch?

**Comment by Tobion** [comment]
2.8 IMO

**Comment by mnapoli** [comment]
Thanks, I've created #869
