### ISSUE TITLE
composer.json is Empty after instalation of Symfony

### ISSUE THREAD

**Issue by sinner** [symfony/symfony-standard#876]
composer.json file is empty after instalation of Symfony Standar Edition 2.7.

**Comment by ogizanagi** [comment]
How did you install the Symfony Standard Edition ?

**Comment by sinner** [comment]
I run on the terminal:

```sh
symfony new proyectName
```

**Comment by ogizanagi** [comment]
I cannot reproduce the issue with both 1.1.7 version and last (1.3) version of the installer.
Which version of the installer do you use ?
Anyway, it seems to be a `symfony-installer` issue. So it should be opened [on this repository](https://github.com/symfony/symfony-installer/issues) if confirmed.

**Comment by sinner** [comment]
Yes is weird... The version I used was 1.1.7

**Comment by Tobion** [comment]
Closing for the reasons provided by @ogizanagi
