### ISSUE TITLE
Test code without required depedency

### ISSUE THREAD

**Issue by flip111** [symfony/symfony-standard#880]
https://github.com/symfony/symfony-standard/blob/2.8/src/AppBundle/Tests/Controller/DefaultControllerTest.php#L7

https://github.com/symfony/framework-bundle/blob/master/Test/WebTestCase.php#L21

https://github.com/symfony/framework-bundle/blob/master/Test/KernelTestCase.php#L22

missing dependency on php-unit

https://github.com/symfony/symfony-standard/blob/2.8/composer.json#L21-L23

**Comment by stof** [comment]
We already rejected it many times (search for PHPUnit in the issue tracker), as the recommended way to install PHPUnit is through the phar
