### ISSUE TITLE
Unexpected "javascripts" tag

### ISSUE THREAD

**Issue by mohamedaymenkarmous** [symfony/symfony-standard#885]
Hi all, I don't know why the AsseticBundle have been removed and I think that my problem is due to this action
After the last updates I have this error:

    request.CRITICAL: Uncaught PHP Exception Twig_Error_Syntax: "Unexpected "javascripts" tag  
    (expecting closing tag for the "block" tag defined near line 8) in "::template_parent.html.twig"
    at line 8." at /var/www/myfolder/vendor/twig/twig/lib/Twig/Parser.php
    line 167 {"exception":"[object] (Twig_Error_Syntax(code: 0):
    Unexpected \"javascripts\" tag (expecting closing tag for the \"block\" tag defined near line 8)
    in \"::template_parent.html.twig\" at line 8.
    at /var/www/myfolder/vendor/twig/twig/lib/Twig/Parser.php:167)"} []

And the file "template_parent.html.twig" contain:

     {% block javascripts %}
        {% javascripts
               'bundles/securinetsfrontoffice/js/jquery-1.9.1.js'
               'bundles/securinetsfrontoffice/js/jquery-ui-1.10.3.custom.js'
        %}
        <script type="text/javascript" src="{{ asset_url }}"></script>
        <script language="javascript">
            //some code
         </script>
        {% endjavascripts %}
     {% endblock %}

So I removed the {% javascripts %} {% endjavascripts %} like this

     {% block javascripts %}
        <script type="text/javascript" src="../bundles/securinetsfrontoffice/js/jquery-1.9.1.js"></script>
        <script type="text/javascript" src="../bundles/securinetsfrontoffice/js/jquery-ui-1.10.3.custom.js"></script>
        <script language="javascript">
            //some code
         </script>
     {% endblock %}

And the code worked
So what if my files are not in the /web folder ? (Example: /app/Ressources/public/)
I haven't the right to leave the /web folder

**Comment by Pierstoval** [comment]
You can add the AsseticBundle manually by running `composer require symfony/assetic-bundle` or adding it back to the `require` section in your `composer.json` file.
 
For the second part, you may look at the [asset function documentation](http://symfony.com/doc/current/reference/twig_reference.html#asset) in the twig extension docs, or [how to create and manage assets](http://symfony.com/doc/current/book/templating.html#book-templating-assets) in the templating docs.

**Comment by mohamedaymenkarmous** [comment]
Thanks Pierstoval,
I hope there will be no problem by adding the AsseticBundle or a security flaw related to AsseticBunde

**Comment by Pierstoval** [comment]
There will not, Assetic and its bundle are still supported, they're just not bundled by default to allow users to use different tools to manage assets and frontend tools (like gulp, grunt, etc.)

**Comment by mohamedaymenkarmous** [comment]
I see
Thank you again
