### ISSUE TITLE
symfony 2.3 LTS breaks while updating 2.3.24 -> 2.3.25

### ISSUE THREAD

**Issue by c33s** [symfony/symfony-standard#886]
having a installation of symfony 2.3.9 and using propel makes it impossible to apply a patch update to symfony because symfony 2.3.25 introduces a BC break.

    > php app/console
    Symfony version 2.3.9
    ...

    > composer update
    
      - Removing symfony/symfony (v2.3.9)
      - Installing symfony/symfony (v2.3.34)
  
      - Removing sensio/framework-extra-bundle (v2.3.4)
      - Installing sensio/framework-extra-bundle (v3.0.11)

accessing the page (which doesn't use the param converter)
      
    Whoops, looks like something went wrong.

    1/1FatalErrorException: Compile Error: Declaration of Propel\PropelBundle\Request\ParamConverter\PropelParamConverter::apply() must be compatible with Sensio\Bundle\FrameworkExtraBundle\Request\ParamConverter\ParamConverterInterface::apply(Symfony\Component\HttpFoundation\Request $request, Sensio\Bundle\FrameworkExtraBundle\Configuration\ParamConverter $configuration) in src\vendor\propel\propel-bundle\Propel\PropelBundle\Request\ParamConverter\PropelParamConverter.php line 26
    
shouldn't exactly this be prevented by using semver? 

from symfony 2.3.24 to 2.3.25 a different framework-extra-bundle is included (major version jump).

https://github.com/symfony/symfony-standard/blob/v2.3.24/composer.json#L19

    "sensio/framework-extra-bundle": "2.3.*",

https://github.com/symfony/symfony-standard/blob/v2.3.25/composer.json#L20

    "sensio/framework-extra-bundle": "~3.0,>=3.0.2",

this new version changes the interface of the paramconverter, which is a BC break. why introduce such a change in a patch version, which really prevent from simple upgrading.

https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/v2.3.4/Request/ParamConverter/ParamConverterInterface.php#L33

    function apply(Request $request, ConfigurationInterface $configuration);
 
https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/v2.3.4/Request/ParamConverter/ParamConverterInterface.php#L42

    function supports(ConfigurationInterface $configuration);

https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/v3.0.0/Request/ParamConverter/ParamConverterInterface.php#L33

    public function apply(Request $request, ParamConverter $configuration);

https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/v3.0.0/Request/ParamConverter/ParamConverterInterface.php#L42

    public function supports(ParamConverter $configuration);

i know propel is not a first citizen in symfony any more but i still think 

propel bundle 1.4 is for symfony >= 2.4
propel bundle 1.2 is for symfony 2.2 & 2.3

so i have to stick with version 1.2

https://github.com/propelorm/PropelBundle/blob/1.2.15/composer.json#L21

    "conflict": {
      "sensio/framework-extra-bundle": ">=2.4"
      
where still the old interface is used
      
https://github.com/propelorm/PropelBundle/blob/1.2.15/Request/ParamConverter/PropelParamConverter.php#L76

    public function apply(Request $request, ConfigurationInterface $configuration)
    
https://github.com/propelorm/PropelBundle/blob/1.2.15/Request/ParamConverter/PropelParamConverter.php#L149

    public function supports(ConfigurationInterface $configuration)

just adding a conflict, doesn't really help, with this changes (on symfony side and propel bundle side, it still breaks the patch upgrade way, which should always be without BC breaks i think.
      
this topic is not about "just update to 2.4 or to the next LTS version" its about, should this happen? shouldn't BC breaks always be prevented in patch versions? why not introduce this interface change with symfony 2.4?

@havvg @marcj

**Comment by Tobion** [comment]
Just because the default requirment in symfony-standard for `sensio/framework-extra-bundle` changed, doesn't mean you have to do this upgrade too. Have you tried to keep the old `sensio/framework-extra-bundle`? Does it not work?

**Comment by Pierstoval** [comment]
Just rollback your `sensio/framework-extra-bundle` dependency back to `2.3.*` and it should be settled.

**Comment by c33s** [comment]
this issue is not about the problem of solving this by doing a rollback but a question of "should this happen in an LTS version when appying a patch?"

also i prefer to require `"symfony/framework-standard-edition: 2.3.*"` in my project rather than directly using the `composer.json` of the framework-standard-edition.

**Comment by Tobion** [comment]
Requiring `symfony/framework-standard-edition` in composer is not a supported installation method and doesn't make sense. The standard edition is meant as starting code that you should replace not as a library. It's not developed with this in mind. There are potentially several other changes in 2.x that would break for you. For example /symfony/symfony-standard#869 which would load the `AppKernel` twice.

So this is not a valid break but a misuse.
