### ISSUE TITLE
Refactor quotes in all yaml configuration files

### ISSUE THREAD

**Issue by bocharsky-bw** [symfony/symfony-standard#888]
I intend to get rid of all single/double quotes for all scalar values and parameter's references starts with `%` charater in configuration `.yml` files since `%` is not special in Yaml 2, so quoting is not necessary.

Also, I suggest to replace all double quotes with single one for configuration `.yml` files for all service references which starts with `@` character. As @stof pointed in https://github.com/symfony/symfony-demo/issues/246#issuecomment-157686459:
> Double quotes in Yaml require to escape many chars in the string, while single quotes only need to escape single quotes themselves.

**Comment by Tobion** [comment]
Ref #687

**Comment by bocharsky-bw** [comment]
But issue 687 doesn't cover replacing double quotes with single quotes.

**Comment by fabpot** [comment]
Closing as there is nothing to "fix" here.
