### ISSUE TITLE
web/config.php - to version control or not?

### ISSUE THREAD

**Issue by teohhanhui** [symfony/symfony-standard#899]
https://github.com/symfony/symfony-standard/blob/693e1f79e4476ab3810e786300026e63e92252bd/web/config.php#L3-L11 says that the file is overridden by composer install/update.

Is there a reason why it is in version control then?

**Comment by Tobion** [comment]
So you can run it before vendors are installed.

**Comment by bocharsky-bw** [comment]
The same with `SymfonyRequirements.php` file

**Comment by teohhanhui** [comment]
I guess this still means projects which have an automated provisioning (e.g. Docker) set up should remove these files from version control?

**Comment by bocharsky-bw** [comment]
You can't use this files after `git clone` if you delete them from VSC  until you do `composer install`.

**Comment by teohhanhui** [comment]
I guess there's no harm in leaving them around...
