### ISSUE TITLE
Enable name converter for serializer service

### ISSUE THREAD

**Issue by Yakimun** [symfony/symfony-standard#902]
Documentation does not describe the way to connect name converters with default serializer service. How can this be done?

**Comment by Pierstoval** [comment]
Have you looked at the [Serializer documentation](http://symfony.com/doc/current/components/serializer.html) or [this update note about the Serializer](http://symfony.com/blog/new-in-symfony-2-7-serializer-component-improvements)?

**Comment by xabbuh** [comment]
I agree. If you feel that documentation could be improved in some aspects, please open an issue on the documentation repository.

**Comment by michaelperrin** [comment]
@yakimun There is an option for than on the `serializer` config entry.
See http://symfony.com/doc/current/reference/configuration/framework.html#name-converter .

I think I am going to open a PR on the Symfony docs repo to mention that option in the Serializer [How to use](http://symfony.com/doc/current/serializer.html) page too.
