### ISSUE TITLE
Change notation of PHP version

### ISSUE THREAD

**Issue by JHGitty** [symfony/symfony-standard#905]
Currently we use this notation for the PHP version:
```json
"php": ">=5.5.9",
```

What's about this?
```json
"php": "^5.5.9|^7.0"
```

**Comment by Tobion** [comment]
Why does it matter? PHP 8 is irrelevant atm.

**Comment by gnugat** [comment]
@Tobion  it would be consistent with the `^2.3|^3.0` notation used for Symfony Components

**Comment by gnugat** [comment]
Nevermind, looks like it's not used in the SE, just in `symfony/symfony`.

**Comment by JHGitty** [comment]
@gnugat We use the caret operator since version 3 for SE:
https://github.com/symfony/symfony-standard/commit/33004067138953da9d9ba05f775cf95e6acb063c

**Comment by Tobion** [comment]
"php": "^5.5.9|^7.0" and "php": ">=5.5.9", are different things. And I do not agree to forbid php 8 by default. If you think your project is not going to be compatible with php > 7 (whatever that means), feel free to change it in your project.
