### ISSUE TITLE
Add an official way to put a website under maintenance mode 

### ISSUE THREAD

**Issue by jbinfo** [symfony/symfony-standard#920]

**Comment by bocharsky-bw** [comment]
It depends. I think there're many good ways to do it, but add at least one example to the cookbooks section would be nice.

**Comment by Pierstoval** [comment]
:-1: for this, it's really simple to do and it depends on each platform and app. Create a listener that uses a boolean `maintenance` parameter in the config and make this listener redirects to a specific route everytime (or simply render a template, as you wish).

**Comment by Enleur** [comment]
I do this with nginx

**Comment by Tobion** [comment]
:-1:  Too specific

**Comment by bocharsky-bw** [comment]
@Pierstoval Don't forget to clear the cache when this parameter value changed in config.

**Comment by Pierstoval** [comment]
@bocharsky-bw Obviously ;) But one can also manage this in the database and update the option in a small backend... But as said, it's too specific, and every method depends on each developer :)

**Comment by fabpot** [comment]
It was explicitly not added in Symfony 2 as such a mechanism must be managed outside of the framework and the PHP code itself.

**Comment by jbinfo** [comment]
@fabpot I think the idea of a cookbook entry is good, I will invite @weaverryan to check this.
