### ISSUE TITLE
Doctrine Common requires php5.5+, so should Symfony 2.8 requires php5.5 as min version too?

### ISSUE THREAD

**Issue by felipsmartins** [symfony/symfony-standard#921]
Today I've broken (sadly) my deployment when installing symfony (via composer) on OpenShift (php5.4). Some days ago it worked well, but today it does not. Doctrine\Common requires php 5.5 as min version (see this [commit](https://github.com/doctrine/common/commit/637d1dbe4b1d58cb9af1532a12cdbd59e7081453) )now and as Symfony-framework-extra-bundle requires doctrine-common too so I wonder if symfony requires php 5.5 from now, as it depends on doctrine-common. 
This is seems a problem, what you guys think of?

![git](https://cloud.githubusercontent.com/assets/454116/12015179/67197b80-ad17-11e5-865b-48b797f8efe1.png)

**Comment by bocharsky-bw** [comment]
You can manually change PHP requirement version to `5.5+` in your own project based on symfony-standard as well. But for BC Symfony `2.8` still requires `>=5.3.9` and it shouldn't be changed here.

**Comment by Tobion** [comment]
It's just a matter of using the same php version when updating vendors as on the server. Framework-extra-bundle can use any version: https://github.com/sensiolabs/SensioFrameworkExtraBundle/blob/master/composer.json#L15
Btw, there is also #858 if that is what you are experiencing.
