### ISSUE TITLE
Simplify .gitignore (requires Git 2.7.0 or higher)

### ISSUE THREAD

**Issue by nicwortel** [symfony/symfony-standard#927]
The latest Git release (2.7.0, released 2016-01-04) makes it easier to un-ignore certain files or directories.

Instead of the current list of patterns for the `var` directory:

```
/var/*
!/var/cache
/var/cache/*
!var/cache/.gitkeep
!/var/logs
/var/logs/*
!var/logs/.gitkeep
!/var/sessions
/var/sessions/*
!var/sessions/.gitkeep
!var/SymfonyRequirements.php
```

this will suffice:

```
/var
!/var/cache/.gitkeep
!/var/logs/.gitkeep
!/var/sessions/.gitkeep
!/var/SymfonyRequirements.php
```

(note that a [bug](http://thread.gmane.org/gmane.comp.version-control.git/283378/focus=283430) prevents this from working if you use `/var/` (with a trailing slash), so for the time being use `/var` instead)

How long should we wait before updating the `.gitignore` file (which will only work for Git 2.7.0 or higher)?

**Comment by Pierstoval** [comment]
Actually, as Git update on Windows is certainly made less often than on Linux, according to the fact that Git 2 was unavailable for Windows for some months after its release (IIRC, I remember I had the problem) , also Debian 7 has only git 1.7 and the backports have only 1.9, I think it's not safe for now, even if I'd love to implement this

**Comment by fabpot** [comment]
Closing as we don't want to break things for older versions of Git.
