### ISSUE TITLE
Setting config.platform.php setting to hardcoded 5.3.9 causes issues

### ISSUE THREAD

**Issue by zerkms** [symfony/symfony-standard#933]
> doctrine/migrations v1.2.2 requires php >=5.4.0 -> your PHP version (5.5.9-1ubuntu4.14) or value of "config.platform.php" in composer.json does not satisfy that requirement.`

So I believe it should be removed from `composer.json` (at least for `v2.8`)

It's also hardcoded as `5.5.9` for the `master`, which is not obvious what reason for either.

**Comment by bocharsky-bw** [comment]
@zerkms Please, check discussion in https://github.com/symfony/symfony-standard/issues/858 about `config.platform.php`. But you can delete `config.platform.php` for your project, Symfony SE is simply quick start template for you.

**Comment by zerkms** [comment]
Thanks

**Comment by xabbuh** [comment]
see symfony/symfony-installer#236 for a proposal to do this in the installer
