### ISSUE TITLE
Project naming conventions: Symfony2 vs Symfony3

### ISSUE THREAD

**Issue by frankdejonge** [symfony/symfony-standard#941]
While the project's version is now at its 3rd major, there are still references to `Symfony2`. An example of this is the requirements checker. Should this be converted to `Symfony3`? Just checking before spending some time on a PR.

**Comment by javiereguiluz** [comment]
Nowadays we just use `Symfony` without any version reference for everything (code, docs, etc.)  However, when removing the version number breaks things, we maintain it (example: https://github.com/symfony/symfony/pull/17593)

**Comment by frankdejonge** [comment]
@javiereguiluz so a PR removing it from the symfony-standard requirements check would be :+1: then?

**Comment by frankdejonge** [comment]
A PR fixing this is open here: https://github.com/symfony/symfony-standard/pull/942

**Comment by frankdejonge** [comment]
Apparently this issue is fixed in 4 PR's already.
