### ISSUE TITLE
Minor inconsistency in AppKernel

### ISSUE THREAD

**Issue by iltar** [symfony/symfony-standard#944]
Every once in a while I "sync" (more of an adapt) my kernel to the SE version. When checking the `getRootDir()` I saw some inconsistencies. Sometimes `__DIR__` is being used and sometimes it's `$this->getRootDir()`. Shouldn't all of them use the method call instead?

https://github.com/symfony/symfony-standard/blob/master/app/AppKernel.php#L31-L49

**Comment by bocharsky-bw** [comment]
This already was discussed in https://github.com/symfony/symfony-standard/pull/914

**Comment by iltar** [comment]
I think this should be documented somewhere as people who simply sync it like I do will not understand this just by looking at the code.

**Comment by Tobion** [comment]
Feel free to document this as you see fit.
