### ISSUE TITLE
Allowed memory size of xxxxx bytes exhausted (tried to allocate 65488 bytes)

### ISSUE THREAD

**Issue by abdielcs** [symfony/symfony-standard#945]
I'm getting this error in a symfony 2.7.9 almost fresh installation, I thought that could be related to one specific bundle but happens with all that I try. The problem occurs when I override any template from a bundle in the app/Resources folder. 

```
Allowed memory size of 1073741824 bytes exhausted (tried to allocate 65488 bytes) in C:\xampp\htdocs\symfony\2.7\install\source\WiseCar\app\cache\dev\classes.php on line 3195
Allowed memory size of 1073741824 bytes exhausted (tried to allocate 65488 bytes) in C:\xampp\htdocs\symfony\2.7\install\source\WiseCar\vendor\symfony\symfony\src\Symfony\Bundle\TwigBundle\Loader\FilesystemLoader.php on line 139
Allowed memory size of 1073741824 bytes exhausted (tried to allocate 65488 bytes) in C:\xampp\htdocs\symfony\2.7\install\source\WiseCar\app\cache\dev\classes.php on line 4833 
```
In those lines in classes.php I found 
```
protected function loadTemplate($template, $templateName = null, $line = null, $index = null)
{
..
return $this->env->loadTemplate($template, $index); //line 4833 
..
}
```
and 
```
public function loadTemplate($name, $index = null)
{
$cls = $this->getTemplateClass($name, $index); //line 3195
..
}

```
In the case of FilesystemLoader.php there is no line 139.

I't happen overriding the layout of FOSUserBundle and also with layout of EasyAdminBundle. No matter how much I increase the memory_limit in php.ini, it always happen, so it look like an infinite loop.
Thanks in advance

**Comment by hacfi** [comment]
@abdielcs This is not the right repository for your issue. I’d ask at https://github.com/FriendsOfSymfony/FOSUserBundle and ideally also post the code how you try to override it. If the issue really is with twig then https://github.com/twigphp/Twig would be the right place to ask.

**Comment by abdielcs** [comment]
@hacfi Thanks a lot, my mistake.
