### ISSUE TITLE
Consider adding a requirement check for ICU

### ISSUE THREAD

**Issue by javiereguiluz** [symfony/symfony-standard#952]
### Problem

* Symfony uses the ICU data bundle in Symfony
* Twig (e.g. [localizedcurrency extension](http://twig.sensiolabs.org/doc/extensions/intl.html#localizedcurrency)) uses the ICU data installed in your computer.

If you computer uses an old ICU version, you'll get different results in Symfony and Twig (e.g. https://github.com/symfony/symfony/issues/15007).

### Solution

Should we display a warning message when the ICU version of the user is older than the one included in Symfony?

**Comment by Pierstoval** [comment]
I'd say yes, we should display a warning, but IIRC, it's something to do also in SensioDistributionBundle which generates the requirements file.

Recommending to update a dependency when it's outdated sounds relevant to me, as long as it is still a recommendation :+1:

**Comment by rvanlaak** [comment]
There is quite some confusion around intl and what versions to use. Especially when you come from an earlier version like 2.1 a lot has changed. So a warning would be great.

**Comment by jakzal** [comment]
It's actually hard to come up with a good warning message. Please have a look at https://github.com/sensiolabs/SensioDistributionBundle/pull/262
