### ISSUE TITLE
Add AppKernel and AppCache to classmap

### ISSUE THREAD

**Issue by sagikazarmark** [symfony/symfony-standard#955]
Not sure if this is a good idea, but it would remove the need for manually requiring it in app_*.php and console files.

**Comment by xabbuh** [comment]
The good news is that we did this with #897. :)

**Comment by sagikazarmark** [comment]
Ah, sorry. I had this in my mind since October, but never made it to create an issue and I was too lazy to check if it happened already or not.

**Comment by sagikazarmark** [comment]
Would it be a good idea to do the same for SymfonyRequirements file? Or since it is generated, it might not?
