### ISSUE TITLE
config.platform.php setting

### ISSUE THREAD

**Issue by gromo89** [symfony/symfony-standard#962]
Why version of PHP is overriten in composer.json file?
I wanted to create project that uses at least php 5.6.0 (::class) and got error that my PHP version does not satisfy that requirement while my version of PHP is 5.6.20

**Comment by xabbuh** [comment]
We need to set the version so that the builds script is able to build archives that are compatible with PHP 5.3 too. You can either use the Symfony installer which removes the setting when the installation has finished or Manuals remove update the file when cloning this package.

**Comment by gnugat** [comment]
You can also use the `--ignore-platform-reqs` option from composer.
