### ISSUE TITLE
AppKernel::registerBundles issue

### ISSUE THREAD

**Issue by clubdesarrolladores** [symfony/symfony-standard#963]
Hi.

We must change the default code of AppKernel::registerBundles moving this 3 bundles from test or dev enviroment to production:

```php
$bundles[] = new Sensio\Bundle\DistributionBundle\SensioDistributionBundle();
$bundles[] = new Sensio\Bundle\GeneratorBundle\SensioGeneratorBundle();
$bundles[] = new Sensio\Bundle\FrameworkExtraBundle\SensioFrameworkExtraBundle();
```

Otherwise we have this exception.

```
request.CRITICAL: Uncaught PHP Exception Symfony\Component\Config\Exception\FileLoaderLoadException: "Cannot load resource "@MyCompanySaleBundle/Controller/Backend/". Make sure the "MyCompanySaleBundle" bundle is correctly registered and loaded in the application kernel class. If the bundle is registered, make sure the bundle path "@MyCompanySaleBundle/Controller/Backend/" is not empty." at /home/andresgo/staging/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/Loader.php line 73 {"exception":"[object] (Symfony\\Component\\Config\\Exception\\FileLoaderLoadException(code: 0): Cannot load resource \"@MyCompanySaleBundle/Controller/Backend/\". Make sure the \"MyCompanySaleBundle\" bundle is correctly registered and loaded in the application kernel class. If the bundle is registered, make sure the bundle path \"@MyCompanySaleBundle/Controller/Backend/\" is not empty. at /home/andresgo/staging/vendor/symfony/symfony/src/Symfony/Component/Config/Loader/Loader.php:73)"}
```

We dont see this error in localhost, but in several servers online we have this error.
We use 2.7

Thanks in advance.

**Comment by Pierstoval** [comment]
Why do you need these bundles in production?

By the way, have you tried clearing the `prod` cache and optimizing the autoloader?

**Comment by clubdesarrolladores** [comment]
We dont need these bundles in production, but if we not load these bundles, we have the exception.
Clear cache is the first task i do in deployment.

**Comment by xabbuh** [comment]
You need the SensioFrameworkExtraBundle for the annotations. But the Symfony Standard Edition always enables it. The other two bundles are not needed in the production environment.

**Comment by hacfi** [comment]
First make sure what @xabbuh mentioned. Then check if you actually have controllers in your `MyCompanySaleBundle` under `Controller/Backend`. Maybe you forgot to push those controllers but added the reference in your routing.

**Comment by clubdesarrolladores** [comment]
The code is fine. The controller exists en Controller/Backend. In localhost this problem doesnt happens.
So what can be the cause of Symfony Standard Edition do not enable annotations?

**Comment by xabbuh** [comment]
Did you accidentally move the SensioFrameworkExtraBundle to the list of bundles that are only enabled in the dev environment?

**Comment by Pierstoval** [comment]
I think it might be an autoload issue, maybe because the file doesn't exist or autoloading fails

**Comment by clubdesarrolladores** [comment]
Hi, 
@xabbuh i do intentionally, it is the only way it work for me in this project.
@Pierstoval The files and classes exists. Actually, in localhost works fine.

:(

**Comment by hacfi** [comment]
@clubdesarrolladores You always need the `SensioFrameworkExtraBundle`! If you enable it in prod as well everything will work fine.

**Comment by clubdesarrolladores** [comment]
You are right @hacfi 
This project was a upgrading from 2.4 o 2.5, maybe in these releases SensioFrameworkExtraBundle is no required, but in 2.7.

I close this issue, seems to be a own error.

**Comment by Pierstoval** [comment]
SensioFrameworkExtraBundle is not "required" all the time, but it is if you use some special annotations like `Route` or `Method` in you controllers for example.
