### ISSUE TITLE
Disable channels in production by default

### ISSUE THREAD

**Issue by JHGitty** [symfony/symfony-standard#966]
Why are these channels only disabled on ``dev`` environment but not for the ``prod`` environment?

https://github.com/symfony/symfony-standard/blob/master/app/config/config_dev.yml#L20-L23
(Line 20 and Line 23)

**Comment by javiereguiluz** [comment]
@JHGitty because `dev` logs everything and those channels are useless most of the times. In `prod` we log nothing unless something bad happens. In those cases, it's better to log everything just in case.

**Comment by JHGitty** [comment]
Okay, I also think so! Just want to be sure that this was not a mistake and really planned. Thanks! :+1:

**Comment by stof** [comment]
those channels are also very verbose (a channel giving information useful only in special case but writing only a single message for some requests would not be an issue). The goal is to avoid flooding the logs, hiding more useful messages.
