### ISSUE TITLE
Disallow --no-debug for dev environment

### ISSUE THREAD

**Issue by JHGitty** [symfony/symfony-standard#968]
If you run ``php bin/console --env=dev --no-debug`` you may get an error:

```
[Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException]                                   
 The service "profiler" has a dependency on a non-existent service "debug.security.access.decision_manager". 
```

We should disallow the usage of ``--no-debug`` on all environments except ``prod`` by default. Or we should show a warning if you use ``--no-debug`` without ``--env=prod``.

I also thought about to fix this issue but I didn't find a clean solution. See: https://github.com/symfony/symfony-standard/issues/967

**Comment by azatyan** [comment]
In capistrano you can fix with this way

set :symfony_env_prod, "dev"
set :symfony_debug, true

**Comment by stof** [comment]
> We should disallow the usage of --no-debug on all environments except prod by default.

That's a very bad idea. I have more environments than just prod and dev, and some of them make perfect sense in no-debug mode.

**Comment by JHGitty** [comment]
Another idea: We just add a warning if you'll use `--no-debug` with environment `dev`? We could add this warning to the `bin/console` code.

**Comment by psampaz** [comment]
Is this related to Symfony 3.1? 

I just show this error today after upgrading from 3.0.6 to 3.1

I rolled back  to 3.0.6 and everything worked fine.

**Comment by Pierstoval** [comment]
> Another idea: We just add a warning if you'll use --no-debug with environment dev?
> We could add this warning to the bin/console code.

That's almost the same as @stof warned :confused:

**Comment by JHGitty** [comment]
Hm, not exactly? Just add a warning for `dev` and not for any other environment that are added by the developer?

@psampaz Good question, I'll check it later.

**Comment by steve-todorov** [comment]
I'm experiencing the very same exception after upgrading from 3.0 to 3.1. I can't even run my phpunit test cases because this exception occurs on every test case. I'm not quite sure what's causing it. Any ideas?

**Comment by JHGitty** [comment]
@steve-todorov Just don't use `--no-debug` on your dev environment?!

**Comment by stof** [comment]
@javiereguiluz I think the code enabling ``debug.security.access.decision_manager`` is broken. It should be based on whether the profiler is enabled instead of being based on the debug mode (or the security panel should be disabled when the profiler is enabled but this service is not, which looks wrong to me). could you check it as you wrote it initially ?

On a side note, this Debug implementation also causes issues, because it does not handle having another bundle decorating it first (as it typehints an implementation rather than the interface). See https://github.com/schmittjoh/JMSSecurityExtraBundle/issues/207 for instance.

**Comment by javiereguiluz** [comment]
@stof let's see if https://github.com/symfony/symfony/pull/18934 solves some of these issues. Thanks.

**Comment by steve-todorov** [comment]
@JHGitty How would you set `--no-debug` when running `phpunit -c phpunit.xml.dist`? Setting the environment variables `SYMFONY_ENV` and `SYMFONY_DEBUG` in `phpunit.xml.dist` produce the same exception:
```
<php>
        <env name="SYMFONY_ENV"   value="dev" />
        <env name="SYMFONY_DEBUG" value="1" />
</php>
``` 

@javiereguiluz I've tried your code and it doesn't seem to be fixing the problem yet - I still receive the same exception.
