### ISSUE TITLE
[PHPUnit Bridge] ClockMock and DnsMock cannot detect project Tests namespace

### ISSUE THREAD

**Issue by teohhanhui** [symfony/symfony-standard#969]
The namespace for tests used in the Symfony Standard Edition starts with `Tests\\`:

https://github.com/symfony/symfony-standard/blob/c20cbaa77f10be17d63781ff6b90920cbcdfaebd/composer.json#L11

which is not matched by

https://github.com/symfony/phpunit-bridge/blob/f5e7cdc9b5cd3f7d9b0228692cd6ec5736c3b074/ClockMock.php#L77

and

https://github.com/symfony/phpunit-bridge/blob/f5e7cdc9b5cd3f7d9b0228692cd6ec5736c3b074/DnsMock.php#L169

We should make sure it's supported out of the box.

**Comment by nicolas-grekas** [comment]
Please submit a PR...

**Comment by teohhanhui** [comment]
@nicolas-grekas Do we fix this in PhpUnit Bridge?

**Comment by nicolas-grekas** [comment]
I believe yes, let's have a try. I'm not sure this is a bug fix thought (but others my disagree?)
