### ISSUE TITLE
app_dev.php is different when using composer or symfony installer from the one here in github

### ISSUE THREAD

**Issue by RodolVelasco** [symfony/symfony-standard#978]
I downloaded 2.8.6 version of symfony with composer and syfomny installer and when checking app_dev.php here in github they were different. I had to replace it with one here in github because I was getting next error.

`You are not allowed to access this file. Check app_dev.php for more information.`

**Comment by javiereguiluz** [comment]
This is very strange. Can you please re-check that the exact same Symfony version was installed in both cases? Thanks!

**Comment by RodolVelasco** [comment]
This is weird. I have redone the process for composer and symfony installer and everything is ok for 2.8.*
