### ISSUE TITLE
[DX] Exception Page Trace should only show own code by default

### ISSUE THREAD

**Issue by ofbeaton** [symfony/symfony-standard#980]
In dev mode, stack traces displayed on the web have a nice template showing the exception message, http status code, exception class and a stack trace, along with a code excerp.

In many cases, I would posit most cases, the code excerp is in a vendor included library. This isn't usually because a problem with those packages, but because of code you did earlier in the trace.

Looking at a stack trace I had recently when I had a typo in an Entity name for doctrine, it is 21 items deep, and only 2 are in my application.

```
Unknown Entity namespace alias 'MyDatabaseBundle'.

in vendor/doctrine/orm/lib/Doctrine/ORM/ORMException.php at line 271   -
     */
    public static function unknownEntityNamespace($entityNamespaceAlias)
    {
        return new self(
            "Unknown Entity namespace alias '$entityNamespaceAlias'."
        );
    }
at ORMException ::unknownEntityNamespace ('MyDatabaseBundle') 
in vendor/doctrine/orm/lib/Doctrine/ORM/Configuration.php at line 196   + 
at Configuration ->getEntityNamespace ('MyDatabaseBundle') 
in vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php at line 965   + 
at Parser ->AbstractSchemaName () 
in vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php at line 1702   + 
at Parser ->RangeVariableDeclaration () 
in vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php at line 1557   + 
at Parser ->IdentificationVariableDeclaration () 
in vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php at line 1292   + 
at Parser ->FromClause () 
in vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php at line 874   + 
at Parser ->SelectStatement () 
in vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php at line 843   + 
at Parser ->QueryLanguage () 
in vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php at line 268   + 
at Parser ->getAST () 
in vendor/doctrine/orm/lib/Doctrine/ORM/Query/Parser.php at line 351   + 
at Parser ->parse () 
in vendor/doctrine/orm/lib/Doctrine/ORM/Query.php at line 281   + 
at Query ->_parse () 
in vendor/doctrine/orm/lib/Doctrine/ORM/Query.php at line 293   + 
at Query ->_doExecute () 
in vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php at line 969   + 
at AbstractQuery ->executeIgnoreQueryCache (null, '1') 
in vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php at line 924   + 
at AbstractQuery ->execute (null, '1') 
in vendor/doctrine/orm/lib/Doctrine/ORM/AbstractQuery.php at line 727   + 
at AbstractQuery ->getResult () 
in src/AppBundle/Controller/AlarmController.php at line 85   + 
at AlarmController ->indexAction (object(Request)) 
at call_user_func_array (array(object(AlarmController), 'indexAction'), array(object(Request))) 
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php at line 148   + 
at HttpKernel ->handleRaw (object(Request), '1') 
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php at line 66   + 
at HttpKernel ->handle (object(Request), '1', true) 
in vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php at line 169   + 
at Kernel ->handle (object(Request)) 
in web/app_dev.php at line 35   + 
```

My suggestion is that instead we only display non-vendor code by default, and include a link at the bottom of the trace to "include vendor code" to show it. Don't need to renumber, just hide any items in `vendors/`. It would look like this:

```
Unknown Entity namespace alias 'MyDatabaseBundle'.

at AbstractQuery ->getResult () 
in src/AppBundle/Controller/AlarmController.php at line 85   -
            throw new \RuntimeException('invalid order filter: '.$order);
        }
        $query = $em->createQuery($dql);
        $results = $query->getResult();
        // set state
        $state = 'active';

at Kernel ->handle (object(Request)) 
in web/app_dev.php at line 35   + 
```

This shows me the two items in my app, from where the app came in at app_dev, to where the error is, in AlarmController. It's true in this case because the $dql variable is a bit above, the excerp wasn't useful, but it often will.

This would make the exception page much more useful to people using the symfony standard edition, and make the errors much easier to understand.

In my opinion, an error that is hard to understand is a bug, and should be treated as such.

**Comment by ofbeaton** [comment]
While we are talking about the exception page, how is the `logs` section useful?

```
INFO - Matched route "{route}". 
DEBUG - Read existing security token from the session. 
DEBUG - User was reloaded from a user provider. 
DEBUG - Notified event "{event}" to listener "{listener}". 
DEBUG - Notified event "{event}" to listener "{listener}". 
DEBUG - Notified event "{event}" to listener "{listener}". 
DEBUG - Notified event "{event}" to listener "{listener}". 
DEBUG - Notified event "{event}" to listener "{listener}". 
DEBUG - Notified event "{event}" to listener "{listener}". 
DEBUG - Notified event "{event}" to listener "{listener}". 
DEBUG - Notified event "{event}" to listener "{listener}". 
DEBUG - Notified event "{event}" to listener "{listener}". 
DEBUG - Notified event "{event}" to listener "{listener}". 
DEBUG - Notified event "{event}" to listener "{listener}". 
DEBUG - Notified event "{event}" to listener "{listener}". 
DEBUG - Notified event "{event}" to listener "{listener}". 
DEBUG - Notified event "{event}" to listener "{listener}". 
DEBUG - Notified event "{event}" to listener "{listener}". 
DEBUG - Notified event "{event}" to listener "{listener}". 
CRITICAL - Uncaught PHP Exception Doctrine\ORM\ORMException: "Unknown Entity namespace alias 'MyDatabaseBundle'." at /opt/telephony/myapp/vendor/doctrine/orm/lib/Doctrine/ORM/ORMException.php line 271 
DEBUG - Notified event "{event}" to listener "{listener}". 
DEBUG - Notified event "{event}" to listener "{listener}". 
DEBUG - Notified event "{event}" to listener "{listener}". 
DEBUG - Notified event "{event}" to listener "{listener}". 
DEBUG - Notified event "{event}" to listener "{listener}". 
DEBUG - Notified event "{event}" to listener "{listener}". 
DEBUG - Notified event "{event}" to listener "{listener}". 
DEBUG - Notified event "{event}" to listener "{listener}". 
DEBUG - Notified event "{event}" to listener "{listener}". 
DEBUG - Notified event "{event}" to listener "{listener}". 
DEBUG - Notified event "{event}" to listener "{listener}". 
DEBUG - Notified event "{event}" to listener "{listener}". 
DEBUG - Notified event "{event}" to listener "{listener}". 
DEBUG - Notified event "{event}" to listener "{listener}". 
DEBUG - Notified event "{event}" to listener "{listener}". 
DEBUG - Notified event "{event}" to listener "{listener}". 
```

Shouldn't the `{route}` `{event}` and `{listener}` lines show more useful information?

**Comment by javiereguiluz** [comment]
@ofbeaton I agree with your first feature request. Exceptions should focus first on your own code. Our intention is to redesign the exception pages soon to match the new Symfony style, so we'll try to make it more modern *and* more useful.

---

Regarding the second question, are those the entire log messages you get? For example, in the Symfony Demo with Symfony 3.1 I get these:

```
[2016-06-05 21:53:18] request.INFO: Matched route "{route}". {"route":"blog_post","route_parameters":{"_controller":"AppBundle\\Controller\\BlogController::postShowAction","_locale":"en","slug":"lorem-ipsum-dolor-sit-amet-consectetur-adipiscing-elit","_route":"blog_post"},"request_uri":"http://symfony-demo.dev/app_dev.php/en/blog/posts/lorem-ipsum-dolor-sit-amet-consectetur-adipiscing-elit","method":"GET"} []

[2016-06-05 21:53:18] security.INFO: Populated the TokenStorage with an anonymous Token. [] []

[2016-06-05 21:53:18] request.INFO: Matched route "{route}". {"route":"_wdt","route_parameters":{"_controller":"web_profiler.controller.profiler:toolbarAction","token":"3b3b9e","_route":"_wdt"},"request_uri":"http://symfony-demo.dev/app_dev.php/_wdt/3b3b9e","method":"GET"} []
[2016-06-05 21:53:18] security.INFO: Populated the TokenStorage with an anonymous Token. [] []
```

I see the same useless `Matched route "{route}"` thing ... but I also get the additional information after it.

**Comment by ofbeaton** [comment]
@javiereguiluz yes I copy+pasted the entirety of the "logs" section found on the exception page. There is no additional informational as shown in your paste, which would indeed be the extra information I am missing. I am using Symfony 3.1 as well, displayed in Chrome using a nginx web server. Perhaps I have something misconfigured then?

**Comment by javiereguiluz** [comment]
@ofbeaton I'm not sure about the misconfiguration. This is the monolog config we're using in the config_dev of the demo app: https://github.com/javiereguiluz/symfony-demo/blob/eba83d9436addbb3fdef5244aa65a4ad56b01267/app/config/config_dev.yml#L20-L28

---

Yes, the `{route}` placeholder does not make any sense. That should be the route name. I guess that's a bug.

**Comment by ofbeaton** [comment]
It changed again? I downloaded 3.1@dev on May 9th, 
```
monolog:
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
            channels: [!event]
            
        console:
            type:   console
            channels: [!event, !doctrine]
```
I'll re-download now and make the appropriate changes.

Anyways, {event} could be the event name, and {listener} could be the listener name too.

**Comment by javiereguiluz** [comment]
@ofbeaton I showed you the config of the Symfony Demo app. The Symfony Standard is a different thing. I only showed the config to you in case you can try it to see if you get different results :)

And yes, all the placeholders seem to be missing in log messages.

**Comment by Pierstoval** [comment]
I'm :+1: on "hiding" the non-vendor code in exception pages as long as the full stack trace is available with a single "Hide/show" button.
 
For the logs part, it depends on your monolog config

**Comment by javiereguiluz** [comment]
I'm closing this issue because we'll take care about your first request and I've opened #981 to discuss about the second issue that you mentioned. Thanks!

**Comment by ofbeaton** [comment]
Great to hear @javiereguiluz and very appreciated, though aren't tickets usually closed when the issue is actually resolved? You of course have your own workflow...

**Comment by ofbeaton** [comment]
Should I open a new ticket just for the stack trace improvement then?

**Comment by ofbeaton** [comment]
Since you broke out the 2nd issue into it's own ticket, I renamed the ticket to only reflect the first request. Can it be re-opened now?

**Comment by javiereguiluz** [comment]
@ofbeaton yes, let's reopen it. Thanks!

**Comment by fabpot** [comment]
Closing as there is nothing specific to the standard edition. It should be moved to symfony/symfony insteas.

**Comment by xabbuh** [comment]
@ofbeaton The changes proposed in symfony/symfony#23144 may be of interest to you.
