### ISSUE TITLE
SecurityBundle:Collector:security.html.twig uses profiler_dump in prod env

### ISSUE THREAD

**Issue by vkhramtsov** [symfony/symfony-standard#982]
We are using `AsseticBundle` which parse template for it's needs and while regenerating cache. In `dev` mode no issues shown. In prod mode I have error like `The template "SecurityBundle:Collector:security.html.twig" contains an error: Unknown "profiler_dump" function in "SecurityBundle:Collector:security.html.twig" at line 180. [] []`. 
This error appears because `profiler_dump` defined in `symfony/web-profiler-bundle` package, but kernel uses this module only in `dev` or `test` environment. So here we actually have call to undefined function in `prod` mode.

Also, is it acceptable to use functions from modules, which actually works in `dev` mode only?

Thank you.

**Comment by Pierstoval** [comment]
These templates & functions are used in the profiler which is available only in `dev` mode, I don't know why you are loading these templates in `prod` :confused:

**Comment by vkhramtsov** [comment]
I'm loading only security bundle in prod :). May be it happens because assetic check all templates in any mode.

**Comment by Pierstoval** [comment]
Why security only in prod? Don't you test it? :confused:

**Comment by stof** [comment]
AsseticBundle allows you to select which bundles should be parsed to find Assetic tags. As SecurityBundle does not use Assetic, you could simply remove it from the list of parsed templates (it will make the check for resources faster btw, by checking less paths)

**Comment by vkhramtsov** [comment]
@stof Thank you.

**Comment by eved42** [comment]
I have the same error after installing the last version of Symfony (3.2.*) for a new project and assetic bundle (2.8).
@stof Where is the list of parsed templates ?

**Comment by vkhramtsov** [comment]
I'm not @stof , but you can take a look here
https://github.com/vkhramtsov/php.of.by/blob/master/app/config/config_app_prod.yml

**Comment by stof** [comment]
Well, you should tell AsseticBundle to avoid looking at SecurityBundle.

See http://symfony.com/doc/current/reference/configuration/assetic.html for the config reference. You can configure in which bundles Assetic looks for assets.

**Comment by eved42** [comment]
OK thanks.
