### ISSUE TITLE
Session save_path not working

### ISSUE THREAD

**Issue by syerad** [symfony/symfony-standard#985]
Trying to use a csrf-token validation I encountered a fault in Symfony session handling.

Using the default parameters for session handling:

```yml
handler_id:  session.handler.native_file
save_path:   "%kernel.root_dir%/../var/sessions/%kernel.environment%"
```

the session will never be populated with parameters.
So if I'm trying to validate the csrf-token (Form-Login) I'm always getting a validation error
because the stored session doesn't contain any parameter.

The session-file in `var/sessions` was created but it is empty all the time.

My workaround was to set the` save_path` to` ~`.
This will set the `save_path` to the php session path.

Is it a known problem or am I doing something wrong?

`Symfony 3.1.2`

**Comment by Tobion** [comment]
Looks like a duplicate of https://github.com/symfony/symfony/issues/17715

**Comment by syerad** [comment]
Yes, maybe. 
By the way I'm using Php 5.6

**Comment by syerad** [comment]
I'll try to figure out what's the problem.

**Comment by hacfi** [comment]
@syerad I just tried the settings you posted above and it works fine on my machine with nginx, php 7 (worked with 5.6 previously as well) and Symfony 3.1.2. Try if `chmod -R 0777 var/sessions` helps fixing the permission issues.

**Comment by syerad** [comment]
Hey, I already tried to chmod -R 0777. For me it doesn't work.

**Comment by xabbuh** [comment]
@syerad Do you use Vagrant or the like?

**Comment by syerad** [comment]
Yes, the dev environment is inside a vagrant box.

**Comment by xabbuh** [comment]
@syerad Try move the save path to a directory that is not shared between host and guest.

**Comment by syerad** [comment]
@xabbuh It Works! Thx! Do you have an explanation why it doesn't work using a shared folder?

**Comment by syerad** [comment]
@xabbuh It works! Thx! Do you have any explanation why it's not working using a shared folder?
Permission issues?

**Comment by syerad** [comment]
@xabbuh do you know why using a shared folder for sessions is not working?

**Comment by xabbuh** [comment]
@syerad Sorry, I have no satisfactory explanation for this issue. However, I generally move files that are written by the application (cache, logs, and sessions) out of the shared folder to avoid any issues.

**Comment by syerad** [comment]
Ok, thx +1:

**Comment by bocharsky-bw** [comment]
@xabbuh I'm wondering how do you get an autocompletion in this case? Symfony plugin read a lot of cached files to make autocompletion possible.

**Comment by Iar0** [comment]
@xabbuh Thank u, it solved my problem (symfony 3 on vagrant using homestead)

**Comment by cdoublev** [comment]
Don't you think that this issue should stay open ? `var/sessions` is the default value for the current stable version. It is currently my first experience with Symfony and I spent 1 hour to figure out why my session values could not be writed. There is no warnings in the documentation and I think many people use Vagrant as their environment for development.
