### ISSUE TITLE
Check var directory as documented

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony-standard#987]
From the [documentation](https://symfony.com/doc/current/setup/file_permissions.html);

> One important Symfony requirement is that the var directory must be writable both by the web server and the command line user.

However the symfony requirements checker doesn't check this :) which leads to https://github.com/symfony/symfony/issues/19632

**Comment by ro0NL** [comment]
@fabpot do you think a simple `is_writeable('./var')` will do? Im leaning to creating a tmp file+dir in `./var` and test if that succeeds.. Im not sure whats sufficient here.

Btw this needs to be fixed in SensioDistributionBundle right?

**Comment by fabpot** [comment]
This should be reported on symfony/requirements-checker
