### ISSUE TITLE
[BUG] CLI / parameters.yml database_password escaping

### ISSUE THREAD

**Issue by ofbeaton** [symfony/symfony-standard#989]
For those of use using randomly generated passwords (I used passwordsgenerator.net w/ `Include Symbols` enabled), it can be rather problematic to put them in our `parameters.yml`

They sometimes (in our case often) have `%` and `\` characters inside them, and it's problematic to figure out what has to be escaped where.

After much googling and time spent on stackexchange, nobody's pointed out a good solution.

http://symfony.com/doc/current/components/yaml/yaml_format.html
seems to tell me single quoting the string should do it. That resolves the problem with `\`, but unlike that documentation you still have to escape `%` if there are two of them, or it thinks it's a parameter inside the password.

This isn't just related to editing the file by hand, if you don't have an existing `parameters.yml` and are prompted for the db password on the command line, provide it, it is not properly escape either, resulting in error messages.

Is there any way that this user experience could be improved?

**Comment by xabbuh** [comment]
I am not sure if we can do anything about that. How should some code be supposed to decide whether or not the user entered a percent chracter intentionally?

**Comment by ofbeaton** [comment]
This is a classic case of a prompt not properly escaping user input. If the parameters.yml prompt asks me for the db password, and I enter it at the prompt, then it should escape it properly for the parameters.yml.

Right now it breaks because it doesn't escape it.

**Comment by ofbeaton** [comment]
As a further and separate change to improve behaviour, if said module is unable to connect to the db because of a bad password, it could easily check if there are two % signs in the password and suggest that user might have to escape them. This covers manually edited parameters.yml files not done at the prompt.

**Comment by ofbeaton** [comment]
The last place things could be improved is in documentation, to indicate that special escaping needs to take place, and what needs to be escaped. As I showed in the YAML link above, it doesn't think % needs to be treated special.

**Comment by ofbeaton** [comment]
Can this be tagged/flagged as a bug? Entering db password at the prompt that contains a symfony-specific special character breaks your install. I would hate for this not to get fixed before 3.2

**Comment by stof** [comment]
the escaping of ``%``is not related to the YAML format, but to Symfony parameters (where the ``%`` has a special meaning)

**Comment by raju1986raju** [comment]
you can use [http://randomstrongpasswordsgenerator.com/](url)

**Comment by fabpot** [comment]
Closing as this repo is now closed for feature addition. Flex is the future of Symfony.
