### ISSUE TITLE
Add a functional Docker environment

### ISSUE THREAD

**Issue by dkarlovi** [symfony/symfony-standard#992]
After having fixed symfony/symfony#19681, add a sample docker-compose.yml file with an example how to set everything up and get up&running really fast.

You could use `nginx:alpine` with `php:7.0-fpm-alpine` to make it really small.

**Comment by jakzal** [comment]
:-1:

I think it's out of scope of this repo. Such configuration is too specific to your project and we have rejected similar requests before (for vagrant at least).

**Comment by dkarlovi** [comment]
@jakzal Vagrant and Docker do not have a 1:1 relationship. Where Vagrant is a development tool, Docker is also a production-ready environment which means you could use exactly the same configuration for deployment.

You could argue "too specific for your project" for Swift mailer too for example, your project doesn't need to send mails, yet you still ship mailing by default.

**Comment by Pierstoval** [comment]
@jakzal:
> 👎
> 
> I think it's out of scope of this repo. Such configuration is too specific to your project and we have rejected similar requests before (for vagrant at least).

Yet there is still a Heroku deployment process in the distribution bundle:

https://github.com/sensiolabs/SensioDistributionBundle/blob/master/Composer/ScriptHandler.php#L96-L117

Why not something similar for Docker?

**Comment by jakzal** [comment]
> Vagrant and Docker do not have a 1:1 relationship. Where Vagrant is a development tool, Docker is also a production-ready environment which means you could use exactly the same configuration for deployment.

I'd say there's no relationship between the two. What I mean is these are tools configured per project and we cannot provide a generic configuration for standard edition to be used by everyone.

**Comment by dkarlovi** [comment]
> I'd say there's no relationship between the two.

Then I don't see the reason to mention declining to include Vagrant config here. :)

> What I mean is these are tools configured per project and we cannot provide a generic configuration for standard edition to be used by everyone.

**Everything** is configured per-project. SE is (the way I see it) **a starting point** which should get you up&running ASAP, but you remove everything you don't use (like the mentioned mailer integration, for example).

**Comment by HeahDude** [comment]
I agree with @jakzal here, maintain docker files in this repo is not a good idea.

We share docker files between devs in our own repo to get started quickly depending on php versions, servers and db, so should you.

**Comment by Federkun** [comment]
> how to set everything up and get up&running really fast.

Well, if you're interested, I made this: https://github.com/Federkun/docker-skeleton-php/wiki/Create-a-new-Symfony-application
It's just a starting point.

**Comment by fabpot** [comment]
Closing as this cannot be part of this repo. @dunglas wants to work on Docker support for Symfony Flex, so we might have out of the box support as of Symfony 3.4 or 4.0.

**Comment by dkarlovi** [comment]
@fabpot where is @dunglas working on it (or plans to)?

**Comment by dunglas** [comment]
Here is the current work: https://github.com/dunglas/symfony-docker-skeleton

It's basically the Docker setup of API Platform tweaked for Flex. Please don't send PR on this repo for now but prefer using https://github.com/api-platform/api-platform. I synchronyze them.
