### ISSUE TITLE
Framework bundle assets missing

### ISSUE THREAD

**Issue by ro0NL** [symfony/symfony-standard#995]
The images removed in https://github.com/symfony/symfony/pull/19996 are still referenced :)

web/config.php
![image](https://cloud.githubusercontent.com/assets/1047696/19022896/691adbde-88e2-11e6-8acc-a60ad97c3583.png)

**Comment by xabbuh** [comment]
Thanks for reporting this @ro0NL. But I have to close here as the `config.php` file is provided by the SensioDistributionBundle. I opened an issue over there (see sensiolabs/SensioDistributionBundle#291) to keep track of it.
