### ISSUE TITLE
[Insight] Symfony secret should be changed

### ISSUE THREAD

**Issue by aasanchez** [symfony/symfony-standard#996]
> The secret is the default one from the Symfony Standard Edition

---------------------

_Posted from [SensioLabsInsight](https://insight.sensiolabs.com/projects/446df8f8-528a-4cfd-a80b-262e0e7441f2/analyses/494)_

**Comment by bocharsky-bw** [comment]
What do you mean with this issue?

Symfony SE is just a bootstrap project which you should customize for yourself
